/**
 * Mount test for the EDIT track volume line (TrackVolumeLine.tsx), against the
 * real editor store and the real keyframe selection.
 *
 * The sequence a user makes: every track row draws a line at its fader's
 * level; a right-click on the line adds a keyframe there and selects it; a
 * keyframe drags in value and, once the drag goes sideways, in time, and one
 * undo takes the drag back; Escape during a drag takes it back at once; a drag
 * on a line with no keyframes moves the track fader between one gesture start
 * and one gesture end; the stretch between two keyframes drags as one; the
 * arrow keys nudge the selected keyframe, Delete removes it, Enter opens a
 * field that takes a typed dB value; a right-click on a keyframe opens its
 * menu; a press anywhere else drops the selection; with the cut tool active
 * nothing in the line takes the pointer.
 *
 * It also pins what is easy to get wrong: the line's wrapper and svg take no
 * pointer events, the hit line is one element in both states, every way a drag
 * can end runs one teardown that closes its undo group exactly once, a press
 * that never travels writes nothing, and the pointer math survives CSS zoom.
 *
 * Client-rendered (createRoot on jsdom), in the CcLane.test.tsx pattern.
 *
 *   cd frontend && node node_modules/tsx/dist/cli.mjs src/components/audio/TrackVolumeLine.test.tsx
 */
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import type { AutomationLane, AutomationPoint, EditorTrack } from '../../state/editorStore.ts';

const dom = new JSDOM('<!doctype html><html><body></body></html>', { url: 'http://localhost/', pretendToBeVisual: true });
const win = dom.window;
const globals: Record<string, unknown> = {
  window: win,
  document: win.document,
  navigator: win.navigator,
  HTMLElement: win.HTMLElement,
  HTMLInputElement: win.HTMLInputElement,
  Element: win.Element,
  Node: win.Node,
  Event: win.Event,
  localStorage: win.localStorage,
  getComputedStyle: win.getComputedStyle.bind(win),
  requestAnimationFrame: win.requestAnimationFrame.bind(win),
  cancelAnimationFrame: win.cancelAnimationFrame.bind(win),
  IS_REACT_ACT_ENVIRONMENT: true,
};
for (const [key, value] of Object.entries(globals)) {
  Object.defineProperty(globalThis, key, { value, configurable: true, writable: true });
}

/* ── The page the line is drawn on ──────────────────────────────────────────── */

const ZOOM = 100; // px per second
const ROW = 104; // the default row height: the band is 24..94, 70 px tall
const WIDTH = 1000; // ten seconds of timeline
/** Where the lanes sit in the window, in client px. */
const ORIGIN = { x: 40, y: 30 };
/** The shell's CSS zoom. A client point is the row's own point times this. */
let Z = 1;

// jsdom lays nothing out, so the svg is given the rect a browser would report:
// the row's place in the lanes, scaled by the CSS zoom.
win.SVGSVGElement.prototype.getBoundingClientRect = function getRect(this: SVGSVGElement): DOMRect {
  const rowTop = parseFloat((this.parentElement as HTMLElement | null)?.style.top ?? '') || 0;
  const left = ORIGIN.x;
  const top = ORIGIN.y + rowTop * Z;
  const width = WIDTH * Z;
  const height = ROW * Z;
  return { left, top, width, height, right: left + width, bottom: top + height, x: left, y: top, toJSON: () => ({}) } as DOMRect;
};

// jsdom has no pointer capture. These stand-ins record who took it and who let go.
const captures: Array<[string, Element, number]> = [];
Object.assign(win.Element.prototype, {
  setPointerCapture(this: Element, id: number) { captures.push(['set', this, id]); },
  releasePointerCapture(this: Element, id: number) { captures.push(['release', this, id]); },
});

const { TrackVolumeLines, grabbedKeyframes } = await import('./TrackVolumeLine.tsx');
const { useEditorStore, beginUndoStep } = await import('../../state/editorStore.ts');
const { useVolumeKeyframes, volumeLaneOf, volumeTarget } = await import('../../state/volumeKeyframes.ts');
const { formatVolumeDb, gainToDb, volumeBand, volumeToY } = await import('../../lib/volumeLine.ts');

const React = await import('react');
const { act } = React;
const { createRoot } = await import('react-dom/client');

const store = () => useEditorStore.getState();
const sel = () => useVolumeKeyframes.getState();
const step = (fn: () => void | Promise<void>) => act(async () => { await fn(); });
const near = (a: number, b: number, eps: number, msg: string): void =>
  assert.ok(Math.abs(a - b) <= eps, `${msg} (${a} !~ ${b})`);

const BAND = volumeBand(ROW);
/** The row y of volume `v`. */
const yAt = (v: number): number => volumeToY(v, BAND);

const track = (over: Partial<EditorTrack>): EditorTrack => ({
  id: 't1', name: 'Drums', nameAutoGenerated: false, volume: 0.8, pan: 0,
  mute: false, solo: false, color: '#fff', ...over,
});
const lane = (trackId: string, points: AutomationPoint[], enabled = true): AutomationLane =>
  ({ id: `lane-${trackId}`, target: volumeTarget(trackId), points, enabled });

const pointsOf = (trackId: string): AutomationPoint[] => volumeLaneOf(store().automationLanes, trackId)?.points ?? [];
const trackOf = (trackId: string): EditorTrack => store().tracks.find((t) => t.id === trackId)!;
const undoSteps = (): number => store()._undo.length;

// Every undo group the line opens and closes, in order.
const groupLog: string[] = [];
{
  const { beginUndoGroup, endUndoGroup } = store();
  useEditorStore.setState({
    beginUndoGroup: () => { groupLog.push('begin'); beginUndoGroup(); },
    endUndoGroup: () => { groupLog.push('end'); endUndoGroup(); },
  });
}

/** Two tracks (faders at 0.8 and 0.5), the given volume lanes, an empty undo
 *  history, no selection and the focus on nothing. */
const reset = (lanes: AutomationLane[] = []) => step(() => {
  const focused = win.document.activeElement as HTMLElement | SVGElement | null;
  if (focused && focused !== win.document.body) focused.blur();
  useEditorStore.setState({
    tracks: [track({}), track({ id: 't2', name: 'Bass', volume: 0.5 })],
    clips: [],
    masterFxChain: [],
    automationLanes: lanes,
    automationHolds: {},
    automationMode: 'read',
  } as never);
  useEditorStore.setState({ _undo: [], _redo: [] });
  beginUndoStep();
  useVolumeKeyframes.setState({ selected: null, editing: false });
  groupLog.length = 0;
  calls.length = 0;
  seen.length = 0;
  captures.length = 0;
});

/* ── The harness: what WaveformEditor wires ─────────────────────────────────── */

/** What the line reported to the editor. */
const calls: Array<[string, ...unknown[]]> = [];
/** The volume report `i` handed to onFaderChange. */
const sentVolume = (i: number): number => calls[i][2] as number;
/** What reached the lanes container under the line. */
const seen: string[] = [];
/** The editor's snap grid in seconds, 0 for off. */
let grid = 0;

interface HarnessProps {
  /** false while the cut tool is active */
  interactive?: boolean;
  /** The part of the timeline in view, in seconds. All ten of them unless given. */
  fromSec?: number;
  toSec?: number;
}

function Harness({ interactive = true, fromSec = 0, toSec = WIDTH / ZOOM }: HarnessProps) {
  const tracks = useEditorStore((s) => s.tracks);
  const lanes = useEditorStore((s) => s.automationLanes);
  return (
    <div
      data-lanes=""
      onPointerDown={() => seen.push('pointerdown')}
      onContextMenu={() => seen.push('contextmenu')}
      onDoubleClick={() => seen.push('dblclick')}
      onPointerMove={() => seen.push('pointermove')}
      onPointerUp={() => seen.push('pointerup')}
    >
      <TrackVolumeLines
        tracks={tracks}
        lanes={lanes}
        zoom={ZOOM}
        trackHeight={ROW}
        width={WIDTH}
        fromSec={fromSec}
        toSec={toSec}
        interactive={interactive}
        snap={(sec) => (grid > 0 ? Math.round(sec / grid) * grid : sec)}
        timeStep={(coarse) => (coarse ? 1 : 0.25)}
        onFaderChange={(id, v) => {
          calls.push(['change', id, v]);
          useEditorStore.getState().updateTrack(id, { volume: v });
        }}
        onFaderGestureStart={(id) => calls.push(['start', id])}
        onFaderGestureEnd={(id) => calls.push(['end', id])}
        onKeyframeSelected={() => calls.push(['selected'])}
      />
    </div>
  );
}

const host = win.document.createElement('div');
win.document.body.appendChild(host);
let root = createRoot(host);
// Under StrictMode, as the app runs (main.tsx): every effect mounts, cleans up
// and mounts again, which is the order a listener or a teardown has to survive.
const mount = (props: HarnessProps = {}) => step(() => root.render(<React.StrictMode><Harness {...props} /></React.StrictMode>));

const q = <T extends Element>(selector: string): T | null => win.document.querySelector(selector) as T | null;
const row = (id: string) => q<HTMLElement>(`[data-volume-line="${id}"]`)!;
const svg = (id: string) => row(id).querySelector('svg') as SVGSVGElement;
const hit = (id: string) => row(id).querySelector('[data-volume-hit]') as SVGPolylineElement;
const stroke = (id: string) => row(id).querySelector('polyline:not([data-volume-hit])') as SVGPolylineElement;
const handle = (id: string, index: number) => row(id).querySelector(`[data-volume-keyframe="${index}"]`) as SVGCircleElement | null;
const handles = (id: string) => [...row(id).querySelectorAll('[data-volume-keyframe]')];
const chip = (id: string) => row(id).querySelector('[data-volume-keyframe-ui]') as HTMLElement | null;
const field = (id: string) => row(id).querySelector('input') as HTMLInputElement | null;
const menu = () => q<HTMLElement>('[role="menu"]');
const menuRow = (label: string): HTMLButtonElement => {
  const found = [...(menu()?.querySelectorAll('button') ?? [])].find((b) => b.textContent?.startsWith(label));
  assert.ok(found, `the keyframe menu has a "${label}" row`);
  return found as HTMLButtonElement;
};

/** A client point for the row point (x, y) of the track at `index`. */
const client = (index: number, x: number, y: number) => ({
  clientX: ORIGIN.x + x * Z,
  clientY: ORIGIN.y + (index * ROW + y) * Z,
});
/** A pointer event at a row point. Returns false when its default was prevented. */
const ptr = (el: Element, type: string, index: number, x: number, y: number, init: Record<string, unknown> = {}): boolean =>
  el.dispatchEvent(new win.PointerEvent(type, {
    bubbles: true, cancelable: true, pointerId: 1, pointerType: 'mouse', button: 0,
    buttons: type === 'pointerup' ? 0 : 1, ...client(index, x, y), ...init,
  }));
const mouse = (el: Element, type: string, index: number, x: number, y: number, init: Record<string, unknown> = {}): boolean =>
  el.dispatchEvent(new win.MouseEvent(type, {
    bubbles: true, cancelable: true, button: type === 'contextmenu' ? 2 : 0, ...client(index, x, y), ...init,
  }));
const key = (el: Element, k: string, init: Record<string, unknown> = {}): boolean =>
  el.dispatchEvent(new win.KeyboardEvent('keydown', { key: k, bubbles: true, cancelable: true, ...init }));
const valueSetter = Object.getOwnPropertyDescriptor(win.HTMLInputElement.prototype, 'value')!.set!;
const type = (el: HTMLInputElement, text: string) => {
  valueSetter.call(el, text);
  el.dispatchEvent(new win.InputEvent('input', { bubbles: true, inputType: 'insertText', data: text.slice(-1) }));
};

// The keys the timeline's own window shortcuts would also get.
const windowKeys: string[] = [];
win.addEventListener('keydown', (e) => windowKeys.push((e as KeyboardEvent).key));

await reset();
await mount();

/* ── The bare line ──────────────────────────────────────────────────────────── */

// Every track draws a line at its fader's level, and the line is a slider.
{
  assert.equal(stroke('t1').getAttribute('points'), '0.0,38.0 1000.0,38.0', 'the line sits at the fader: 0.8 is y 38');
  assert.equal(hit('t1').getAttribute('points'), '0.0,38.0 1000.0,38.0', 'and the pointer takes it along the same path');
  assert.equal(stroke('t2').getAttribute('points'), '0.0,59.0 1000.0,59.0', 'the second track, at 0.5');
  assert.equal(stroke('t1').getAttribute('stroke'), '#34d399');
  assert.equal(stroke('t1').getAttribute('stroke-width'), '1.5');
  assert.equal(stroke('t1').getAttribute('stroke-opacity'), '0.5', 'a line with no keyframes is faint');

  // Only the line itself takes the pointer: the row's wrapper and the svg take none.
  assert.equal(row('t1').style.top, '0px');
  assert.equal(row('t2').style.top, `${ROW}px`, 'one row down');
  assert.equal(row('t1').style.width, `${WIDTH}px`);
  assert.equal(row('t1').style.height, `${ROW}px`);
  assert.match(row('t1').className, /\bpointer-events-none\b/, 'the wrapper takes no pointer');
  assert.match(row('t1').className, /\bz-26\b/, 'above the clips, under the playhead');
  assert.equal(svg('t1').style.pointerEvents, 'none', 'the svg takes no pointer');
  assert.equal(stroke('t1').getAttribute('pointer-events'), 'none');
  assert.equal(hit('t1').getAttribute('pointer-events'), 'stroke');
  assert.equal(hit('t1').getAttribute('stroke-width'), '12');
  assert.equal(hit('t1').querySelector('title')?.textContent, 'Drag to set the volume. Right-click or double-click to add a keyframe.');
  assert.equal(handles('t1').length, 0);
  assert.equal(chip('t1'), null);

  // HARD RULE 3: a custom control carries a label and valid slider values.
  const s = svg('t1');
  assert.equal(s.getAttribute('role'), 'slider');
  assert.equal(s.getAttribute('tabindex'), '0');
  assert.equal(s.getAttribute('aria-orientation'), 'vertical');
  assert.equal(s.getAttribute('aria-label'), 'Drums volume line, 0 keyframes');
  assert.equal(s.getAttribute('aria-valuemin'), '0');
  assert.equal(s.getAttribute('aria-valuemax'), '1');
  assert.equal(s.getAttribute('aria-valuenow'), '0.8');
  assert.equal(s.getAttribute('aria-valuetext'), '-1.9 dB, no keyframes');
  const help = win.document.getElementById(s.getAttribute('aria-describedby') ?? '');
  assert.ok(help, 'the help the slider is described by is on the page');
  assert.match(help.className, /\bsr-only\b/);
  assert.match(help.textContent ?? '', /Right-click or double-click the line to add a keyframe/);
  assert.equal(svg('t2').getAttribute('aria-describedby'), s.getAttribute('aria-describedby'), 'one help paragraph for every line');
  assert.equal(win.document.querySelectorAll(`#${help.id}`).length, 1);
  assert.equal(win.document.querySelector('label'), null, 'no <label> wraps or names the custom control');
}

/* ── Adding a keyframe ──────────────────────────────────────────────────────── */

// A right-click on the line adds a keyframe at the fader's value and selects
// it. The hit line is the same element before and after.
{
  const hitBefore = hit('t1');
  let notPrevented = true;
  await step(() => { notPrevented = mouse(hitBefore, 'contextmenu', 0, 250, 38); });
  assert.equal(notPrevented, false, 'the browser menu does not open');
  assert.deepEqual(seen, [], 'and the lanes under the line never see the right-click');
  assert.deepEqual(pointsOf('t1'), [{ t: 2.5, v: 0.8 }], 'a keyframe under the pointer, at the fader value');
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.5 }, 'selected');
  assert.equal(undoSteps(), 1, 'lane and keyframe are one undo step');
  assert.deepEqual(calls, [['selected']], 'the editor is told to drop its clip selection');
  assert.equal(win.document.activeElement, svg('t1'), 'the line has the keys');
  assert.equal(hit('t1'), hitBefore, 'the hit line did not remount when the line gained its first keyframe');
  assert.equal(stroke('t1').getAttribute('points'), '0.0,38.0 250.0,38.0 1000.0,38.0', 'the line did not move');
  assert.equal(stroke('t1').getAttribute('stroke-width'), '2', 'the line with the keys is drawn strong');
  assert.equal(stroke('t1').getAttribute('stroke-opacity'), '1');

  // The keyframe is a diamond with a grab circle over it, and its value chip beside it.
  const h = handle('t1', 0);
  assert.ok(h, 'the keyframe has a handle');
  assert.equal(h.getAttribute('cx'), '250');
  near(Number(h.getAttribute('cy')), 38, 1e-9, 'on the line');
  assert.equal(h.getAttribute('r'), '9');
  assert.equal(h.getAttribute('pointer-events'), 'all');
  assert.equal(h.querySelector('title')?.textContent, 'Drag to move. Arrow keys nudge. Double-click to type a value. Right-click for more.');
  const diamond = h.parentElement!.querySelector('rect')!;
  assert.equal(diamond.getAttribute('width'), '9', 'the selected keyframe is the larger diamond');
  assert.equal(diamond.getAttribute('fill'), '#fff');
  assert.equal(diamond.getAttribute('stroke'), '#34d399');
  assert.equal(diamond.getAttribute('pointer-events'), 'none');
  const c = chip('t1');
  assert.ok(c, 'the selected keyframe shows its value');
  const chipKey = c.querySelector('button')!;
  assert.equal(chipKey.textContent, '-1.9 dB');
  assert.equal(chipKey.getAttribute('aria-label'), 'Type a volume for this keyframe');
  assert.match(chipKey.className, /\btext-xs\b/);
  assert.match(chipKey.className, /\bfont-bold\b/, '12 px bold, never thin small text');
  assert.equal(c.style.left, '260px', '10 px to the right of the keyframe');
  assert.equal(c.style.top, '28px', 'centred on it: the chip is 20 px tall');
  assert.match(c.className, /\bpointer-events-auto\b/);

  const s = svg('t1');
  assert.equal(s.getAttribute('aria-label'), 'Drums volume line, 1 keyframe');
  assert.equal(s.getAttribute('aria-valuenow'), '0.8');
  assert.equal(s.getAttribute('aria-valuetext'), '-1.9 dB at 00:02.500');

  // One undo takes back the keyframe and its lane, and the line is the fader again.
  await step(() => store().undo());
  assert.deepEqual(store().automationLanes, []);
  assert.equal(hit('t1'), hitBefore, 'still the same hit line');
  assert.equal(handles('t1').length, 0);
  assert.equal(chip('t1'), null, 'a selection whose keyframe is gone shows nothing');
  await step(() => store().redo());
  assert.equal(handles('t1').length, 1);
}

// The time snaps to the editor's grid, Alt takes it free, and a right-click on
// a keyframe that is already there selects it. A double-click adds one too.
{
  grid = 0.5;
  await step(() => { mouse(hit('t1'), 'contextmenu', 0, 412, 38); });
  assert.deepEqual(pointsOf('t1').map((p) => p.t), [2.5, 4], '4.12 s snapped to the grid');
  await step(() => { mouse(hit('t1'), 'contextmenu', 0, 612, 38, { altKey: true }); });
  assert.deepEqual(pointsOf('t1').map((p) => p.t), [2.5, 4, 6.12], 'Alt leaves the grid');
  const steps = undoSteps();
  await step(() => { mouse(hit('t1'), 'contextmenu', 0, 262, 38); });
  assert.equal(pointsOf('t1').length, 3, '2.62 s snaps onto the keyframe at 2.5: nothing is added');
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.5 }, 'that keyframe is selected');
  assert.equal(undoSteps(), steps);
  seen.length = 0;
  await step(() => { mouse(hit('t1'), 'dblclick', 0, 800, 38); });
  assert.deepEqual(pointsOf('t1').map((p) => p.t), [2.5, 4, 6.12, 8], 'a double-click adds a keyframe');
  assert.deepEqual(sel().selected, { trackId: 't1', t: 8 });
  assert.deepEqual(seen, [], 'and stays with the line');
  assert.ok(pointsOf('t1').every((p) => p.v === 0.8), 'every one on the line, so the line never moved');
  grid = 0;
  // Within 8 px of a keyframe a right-click means that keyframe, off the grid too.
  await step(() => { mouse(hit('t1'), 'contextmenu', 0, 406, 38); });
  assert.equal(pointsOf('t1').length, 4, '6 px from the keyframe at 4 s: nothing is added');
  assert.deepEqual(sel().selected, { trackId: 't1', t: 4 });
  await step(() => { mouse(hit('t1'), 'contextmenu', 0, 412, 38); });
  assert.deepEqual(pointsOf('t1').map((p) => p.t), [2.5, 4, 4.12, 6.12, 8], '12 px from it: a keyframe of its own');
}

/* ── Dragging a keyframe ────────────────────────────────────────────────────── */

// A press, a move and a release on a keyframe change its value. One undo puts
// it back. A press that never travels writes nothing.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }])]);
  const h = handle('t1', 0)!;
  await step(() => { ptr(h, 'pointerdown', 0, 250, 38); });
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.5 }, 'a press selects the keyframe');
  assert.deepEqual(calls, [['selected']]);
  assert.equal(win.document.activeElement, svg('t1'));
  assert.deepEqual(captures, [['set', h, 1]], 'the pressed element takes the pointer capture');
  assert.deepEqual(seen, [], 'the lanes never see the press');

  await step(() => { ptr(h, 'pointermove', 0, 250, 36); });
  assert.deepEqual(groupLog, [], '2 px is still a click: no undo group');
  assert.equal(pointsOf('t1')[0].v, 0.8);
  assert.equal(undoSteps(), 0);

  await step(() => { ptr(h, 'pointermove', 0, 250, 31); });
  near(pointsOf('t1')[0].v, 0.9, 1e-9, '7 px up the 70 px band is +0.1');
  assert.equal(pointsOf('t1')[0].t, 2.5, 'a vertical drag leaves the time alone');
  assert.deepEqual(groupLog, ['begin']);
  assert.equal(handle('t1', 0), h, 'the dragged handle is the same element: it holds the capture');
  assert.equal(h.style.cursor, 'grabbing');
  assert.equal(chip('t1')?.textContent, '-0.9 dB', 'the chip follows the value');

  await step(() => { ptr(h, 'pointerup', 0, 250, 31); });
  assert.deepEqual(groupLog, ['begin', 'end'], 'the release closes the group');
  assert.deepEqual(captures, [['set', h, 1], ['release', h, 1]]);
  assert.equal(undoSteps(), 1, 'the whole drag is one undo step');
  assert.deepEqual(seen, [], 'neither the moves nor the release reached the lanes');
  // The capture goes after the release. It must not close the group again.
  await step(() => { h.dispatchEvent(new win.PointerEvent('lostpointercapture', { bubbles: true, pointerId: 1 })); });
  assert.deepEqual(groupLog, ['begin', 'end']);

  await step(() => store().undo());
  assert.deepEqual(pointsOf('t1'), [{ t: 2.5, v: 0.8 }], 'one undo puts the keyframe back');
  assert.equal(undoSteps(), 0);

  // A press and a release with no travel: nothing written, no group, no undo step.
  groupLog.length = 0;
  const before = store().automationLanes;
  await step(() => {
    ptr(h, 'pointerdown', 0, 250, 38);
    ptr(h, 'pointermove', 0, 251, 39);
    ptr(h, 'pointerup', 0, 251, 39);
  });
  assert.equal(store().automationLanes, before, 'the document is the same object');
  assert.deepEqual(groupLog, []);
  assert.equal(undoSteps(), 0);
}

// The time stays put until the drag has gone 6 px sideways, then follows the
// pointer on the grid. Alt takes it free. The selection follows the keyframe.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }, { t: 6, v: 0.8 }])]);
  const h = handle('t1', 0)!;
  await step(() => { ptr(h, 'pointerdown', 0, 250, 38); });
  await step(() => { ptr(h, 'pointermove', 0, 255, 38); });
  assert.deepEqual(groupLog, ['begin'], '5 px is a drag');
  assert.equal(pointsOf('t1')[0].t, 2.5, 'but not yet a move in time');
  assert.equal(undoSteps(), 0, 'and a drag that has changed nothing has recorded nothing');
  await step(() => { ptr(h, 'pointermove', 0, 280, 38); });
  near(pointsOf('t1')[0].t, 2.8, 1e-9, '30 px to the right is 0.3 s');
  near(sel().selected!.t, 2.8, 1e-9, 'the selection follows the keyframe');
  assert.equal(pointsOf('t1')[0].v, 0.8, 'a sideways drag leaves the value alone');
  grid = 0.5;
  await step(() => { ptr(h, 'pointermove', 0, 290, 38); });
  assert.equal(pointsOf('t1')[0].t, 3, 'on the grid');
  await step(() => { ptr(h, 'pointermove', 0, 290, 38, { altKey: true }); });
  near(pointsOf('t1')[0].t, 2.9, 1e-9, 'Alt leaves the grid');
  grid = 0;
  // It stops short of the keyframe after it and never passes it.
  await step(() => { ptr(h, 'pointermove', 0, 900, 38); });
  near(pointsOf('t1')[0].t, 5.97, 1e-9, 'held 0.03 s off its neighbour');
  assert.equal(pointsOf('t1').length, 2);
  assert.equal(handle('t1', 0), h, 'still the same handle element');
  await step(() => { ptr(h, 'pointerup', 0, 900, 38); });
  assert.equal(undoSteps(), 1, 'one undo step for all of it');
  assert.equal(sel().editing, false);
}

// Shift is a fine drag at a quarter of the speed. Pressing it or letting it go
// mid-drag changes the speed from there on and never makes the value jump.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.4 }])]);
  const h = handle('t1', 0)!;
  const y = yAt(0.4);
  await step(() => { ptr(h, 'pointerdown', 0, 250, y); });
  await step(() => { ptr(h, 'pointermove', 0, 250, y - 14); });
  near(pointsOf('t1')[0].v, 0.6, 1e-9, '14 px up is +0.2');
  await step(() => { ptr(h, 'pointermove', 0, 250, y - 28, { shiftKey: true }); });
  near(pointsOf('t1')[0].v, 0.65, 1e-9, 'the next 14 px with Shift is +0.05');
  await step(() => { ptr(h, 'pointermove', 0, 250, y - 42); });
  near(pointsOf('t1')[0].v, 0.85, 1e-9, 'and the 14 px after it, without, +0.2 again');
  await step(() => { ptr(h, 'pointerup', 0, 250, y - 42); });
}

// Several moves in one frame, before any render: the handlers read the live
// document, so the drag starts from what the keyframe holds NOW.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }])]);
  const h = handle('t1', 0)!;
  await step(() => {
    store().updateAutomationPoint('lane-t1', 0, 2.5, 0.4);
    ptr(h, 'pointerdown', 0, 250, 38);
    ptr(h, 'pointermove', 0, 250, 31);
    ptr(h, 'pointermove', 0, 250, 24);
    ptr(h, 'pointerup', 0, 250, 24);
  });
  near(pointsOf('t1')[0].v, 0.6, 1e-9, '0.4 as the store held it, plus 14 px');
  // The same for the fader: the drag starts from the fader as it is, not as it was last drawn.
  await step(() => {
    store().updateTrack('t2', { volume: 0.3 });
    ptr(hit('t2'), 'pointerdown', 1, 400, 59);
    ptr(hit('t2'), 'pointermove', 1, 400, 52);
    ptr(hit('t2'), 'pointermove', 1, 400, 45);
    ptr(hit('t2'), 'pointerup', 1, 400, 45);
  });
  near(trackOf('t2').volume, 0.5, 1e-9, '0.3 as the store held it, plus 14 px');
}

// Alt-click deletes a keyframe: the app's point-delete gesture.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }, { t: 6, v: 0.8 }])]);
  await step(() => { ptr(handle('t1', 1)!, 'pointerdown', 0, 600, 38, { altKey: true }); });
  assert.deepEqual(pointsOf('t1'), [{ t: 2.5, v: 0.8 }]);
  assert.equal(undoSteps(), 1);
  assert.deepEqual(groupLog, [], 'a delete is not a drag');
  assert.equal(sel().selected, null);
}

// Only the primary button drags. Any other button on the line or on a keyframe
// starts nothing, and still never reaches the lanes.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }])]);
  await step(() => {
    ptr(handle('t1', 0)!, 'pointerdown', 0, 250, 38, { button: 2, buttons: 2 });
    ptr(hit('t1'), 'pointerdown', 0, 500, 38, { button: 1, buttons: 4 });
    ptr(hit('t2'), 'pointerdown', 1, 500, 59, { button: 2, buttons: 2 });
  });
  assert.deepEqual(captures, [], 'no capture');
  assert.equal(sel().selected, null, 'no selection');
  assert.deepEqual(seen, []);
  await step(() => { ptr(hit('t2'), 'pointermove', 1, 500, 20); });
  assert.equal(trackOf('t2').volume, 0.5, 'and no drag');
}

// A move or a release over the line that is NOT the line's own drag passes
// through: a Ctrl+drag copy of a clip holds no pointer capture, so its moves
// and its release cross the line on their way to the timeline's handlers.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }])]);
  await step(() => {
    ptr(hit('t1'), 'pointermove', 0, 500, 38);
    ptr(handle('t1', 0)!, 'pointermove', 0, 250, 38);
    ptr(hit('t1'), 'pointerup', 0, 500, 38);
  });
  assert.deepEqual(seen, ['pointermove', 'pointermove', 'pointerup']);
  seen.length = 0;
  // A second finger during a drag is ignored, and the drag goes on.
  const h = handle('t1', 0)!;
  await step(() => { ptr(h, 'pointerdown', 0, 250, 38); });
  await step(() => { ptr(h, 'pointermove', 0, 250, 31); });
  await step(() => { ptr(hit('t1'), 'pointerdown', 0, 600, 31, { pointerId: 2 }); });
  assert.deepEqual(captures, [['set', h, 1]], 'the second pointer captures nothing');
  await step(() => { ptr(hit('t1'), 'pointermove', 0, 600, 80, { pointerId: 2 }); });
  near(pointsOf('t1')[0].v, 0.9, 1e-9, 'and drags nothing');
  await step(() => { ptr(h, 'pointermove', 0, 250, 24); });
  near(pointsOf('t1')[0].v, 1, 1e-9, 'the first pointer still has the keyframe');
  await step(() => { ptr(h, 'pointerup', 0, 250, 24); });
  assert.deepEqual(groupLog, ['begin', 'end']);
}

// The focus ring is for the keyboard. A press focuses the line too (so it has
// the keys) and draws it strong, but puts no ring round the row.
{
  await reset();
  const ringed = (id: string) => /\bring-1\b/.test(svg(id).getAttribute('class') ?? '');
  await step(() => { ptr(hit('t2'), 'pointerdown', 1, 400, 59); });
  await step(() => { ptr(hit('t2'), 'pointerup', 1, 400, 59); });
  assert.equal(win.document.activeElement, svg('t2'));
  assert.equal(stroke('t2').getAttribute('stroke-width'), '2', 'the pressed line is drawn strong');
  assert.equal(ringed('t2'), false, 'with no focus ring for a mouse press');
  // Tab to the next line: a key moved the focus, so the ring shows where it is.
  await step(() => {
    key(svg('t2'), 'Tab');
    svg('t1').focus();
  });
  assert.equal(ringed('t1'), true, 'the keyboard focus shows its ring');
  assert.equal(ringed('t2'), false);
  assert.match(svg('t1').getAttribute('class') ?? '', /\boutline-none\b/, 'its own ring, never the browser outline as well');
  // The mouse takes over on the line that has the ring: the ring goes, the focus stays.
  await step(() => { ptr(hit('t1'), 'pointerdown', 0, 400, 38); });
  await step(() => { ptr(hit('t1'), 'pointerup', 0, 400, 38); });
  assert.equal(win.document.activeElement, svg('t1'));
  assert.equal(ringed('t1'), false, 'a press on the ringed line takes the ring off');
  await step(() => {
    key(svg('t1'), 'Tab');
    svg('t2').focus();
  });
  assert.equal(ringed('t2'), true);
  await step(() => { svg('t2').blur(); });
  assert.equal(ringed('t2'), false, 'no focus, no ring');
  // The focus handed back after a click (a menu closing on a chosen row) is not a keyboard focus.
  await step(() => { win.document.body.dispatchEvent(new win.PointerEvent('pointerdown', { bubbles: true, pointerId: 1 })); });
  await step(() => { svg('t2').focus(); });
  assert.equal(win.document.activeElement, svg('t2'));
  assert.equal(ringed('t2'), false, 'so it shows no ring');
}

// The pointer over the line draws it strong, so it reads as something to grab.
{
  await reset();
  const line = hit('t2');
  assert.equal(stroke('t2').getAttribute('stroke-width'), '1.5');
  await step(() => { line.dispatchEvent(new win.PointerEvent('pointerover', { bubbles: true, relatedTarget: null })); });
  assert.equal(stroke('t2').getAttribute('stroke-width'), '2');
  assert.equal(stroke('t2').getAttribute('stroke-opacity'), '1');
  assert.equal(stroke('t1').getAttribute('stroke-width'), '1.5', 'only the line under the pointer');
  await step(() => { line.dispatchEvent(new win.PointerEvent('pointerout', { bubbles: true, relatedTarget: win.document.body })); });
  assert.equal(stroke('t2').getAttribute('stroke-width'), '1.5');
}

// Only the keyframes in view get a handle. The handle under a drag stays
// mounted when the drag takes it out of view: it holds the pointer capture.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }, { t: 4.05, v: 0.8 }, { t: 6, v: 0.8 }])]);
  await mount({ fromSec: 0, toSec: 4 });
  assert.deepEqual(
    handles('t1').map((el) => el.getAttribute('data-volume-keyframe')),
    ['0', '1'],
    'the keyframe 5 px past the edge is half in view, the one at 6 s is not',
  );
  const h = handle('t1', 1)!;
  await step(() => { ptr(h, 'pointerdown', 0, 405, 38); });
  await step(() => { ptr(h, 'pointermove', 0, 505, 38); });
  near(pointsOf('t1')[1].t, 5.05, 1e-9, 'dragged a second out of view');
  assert.equal(handle('t1', 1), h, 'the same handle element, still mounted');
  await step(() => { ptr(h, 'pointerup', 0, 505, 38); });
  assert.deepEqual(groupLog, ['begin', 'end']);
  assert.deepEqual(handles('t1').map((el) => el.getAttribute('data-volume-keyframe')), ['0'], 'out of view once the drag is over');
  await mount();
  assert.equal(handles('t1').length, 3);
}

/* ── Escape during a drag ───────────────────────────────────────────────────── */

// Escape takes the drag back and swallows the key: neither the line's own
// Escape (deselect) nor the timeline's runs as well.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }])]);
  const h = handle('t1', 0)!;
  await step(() => { ptr(h, 'pointerdown', 0, 250, 38); });
  await step(() => { ptr(h, 'pointermove', 0, 300, 52); });
  near(pointsOf('t1')[0].t, 3, 1e-9, 'dragged in time');
  near(pointsOf('t1')[0].v, 0.6, 1e-9, 'and in value');
  assert.equal(undoSteps(), 1);
  windowKeys.length = 0;
  let notPrevented = true;
  await step(() => { notPrevented = key(svg('t1'), 'Escape'); });
  assert.equal(notPrevented, false);
  assert.deepEqual(windowKeys, [], 'the key stops at the drag');
  assert.deepEqual(pointsOf('t1'), [{ t: 2.5, v: 0.8 }], 'the keyframe is back where it was');
  assert.equal(undoSteps(), 0, 'and the history is where it was');
  assert.deepEqual(groupLog, ['begin', 'end']);
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.5 }, 'the selection went back with it, and was not dropped');
  assert.equal(handles('t1').length, 1);
  // The button is still down. What it does now belongs to no drag.
  await step(() => {
    ptr(h, 'pointermove', 0, 320, 40);
    ptr(h, 'pointerup', 0, 320, 40);
  });
  assert.deepEqual(pointsOf('t1'), [{ t: 2.5, v: 0.8 }]);
  assert.deepEqual(groupLog, ['begin', 'end'], 'the group was closed once');

  // Escape on a press that has not travelled: nothing to take back, and still the drag's key.
  groupLog.length = 0;
  windowKeys.length = 0;
  await step(() => { ptr(h, 'pointerdown', 0, 250, 38); });
  await step(() => { key(svg('t1'), 'Escape'); });
  await step(() => { ptr(h, 'pointermove', 0, 250, 10); });
  assert.deepEqual(pointsOf('t1'), [{ t: 2.5, v: 0.8 }], 'the press was cancelled, so the move drags nothing');
  assert.deepEqual(groupLog, []);
  assert.deepEqual(windowKeys, []);
  await step(() => { ptr(h, 'pointerup', 0, 250, 10); });

  // Escape on a fader drag takes the fader back, between its one start and one end.
  calls.length = 0;
  await step(() => { ptr(hit('t2'), 'pointerdown', 1, 400, 59); });
  await step(() => { ptr(hit('t2'), 'pointermove', 1, 400, 45); });
  near(trackOf('t2').volume, 0.7, 1e-9, 'the fader is up');
  await step(() => { key(svg('t2'), 'Escape'); });
  assert.equal(trackOf('t2').volume, 0.5, 'and back');
  assert.deepEqual(calls.map((c) => c[0]), ['start', 'change', 'end']);
  await step(() => { ptr(hit('t2'), 'pointerup', 1, 400, 45); });
  assert.deepEqual(calls.map((c) => c[0]), ['start', 'change', 'end']);
}

// The undo history holds 100 steps. Once it is full a new step pushes the
// oldest out and the depth stays 100, and Escape still takes the drag back.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }])]);
  await step(() => {
    for (let i = 0; i < 100; i += 1) {
      beginUndoStep();
      store().updateTrack('t2', { volume: i % 2 === 0 ? 0.1 : 0.2 });
    }
  });
  assert.equal(undoSteps(), 100, 'the history is full');
  const h = handle('t1', 0)!;
  await step(() => { ptr(h, 'pointerdown', 0, 250, 38); });
  await step(() => { ptr(h, 'pointermove', 0, 250, 52); });
  near(pointsOf('t1')[0].v, 0.6, 1e-9, 'dragged');
  assert.equal(undoSteps(), 100, 'the depth did not grow');
  await step(() => { key(svg('t1'), 'Escape'); });
  assert.deepEqual(pointsOf('t1'), [{ t: 2.5, v: 0.8 }], 'Escape took the drag back all the same');
  assert.equal(undoSteps(), 99, 'by exactly its one step');
  assert.equal(trackOf('t2').volume, 0.2, 'and none of the edits before it');
  await step(() => { ptr(h, 'pointerup', 0, 250, 52); });
}

/* ── Dragging the bare line ─────────────────────────────────────────────────── */

// A drag on a line with no keyframes moves the track fader, between ONE
// gesture start and ONE gesture end, and is one undo step.
{
  await reset();
  const line = hit('t2');
  await step(() => { ptr(line, 'pointerdown', 1, 400, 59); });
  assert.deepEqual(calls, [], 'a press alone reports nothing and selects nothing');
  assert.equal(win.document.activeElement, svg('t2'), 'but the line takes the keys');
  assert.deepEqual(captures, [['set', line, 1]]);
  await step(() => { ptr(line, 'pointermove', 1, 400, 57); });
  assert.deepEqual(calls, [], '2 px is still a click');
  await step(() => { ptr(line, 'pointermove', 1, 400, 45); });
  assert.deepEqual(calls.map((c) => c[0]), ['start', 'change']);
  near(sentVolume(1), 0.7, 1e-9, '14 px up is +0.2');
  // The level under the pointer shows beside it while the drag is in flight.
  const readout = chip('t2');
  assert.ok(readout, 'a readout beside the pointer');
  assert.equal(readout.tagName, 'SPAN');
  assert.equal(readout.textContent, '-3.1 dB');
  assert.match(readout.className, /\bpointer-events-none\b/, 'it is a readout, not a control');
  assert.equal(readout.style.left, '410px');
  assert.equal(stroke('t2').getAttribute('points'), '0.0,45.0 1000.0,45.0', 'the line is under the pointer');
  // Sideways travel changes nothing on a fader.
  await step(() => { ptr(line, 'pointermove', 1, 460, 45); });
  assert.equal(calls.length, 2);
  await step(() => { ptr(line, 'pointermove', 1, 460, 52); });
  await step(() => { ptr(line, 'pointerup', 1, 460, 52); });
  assert.deepEqual(calls.map((c) => c[0]), ['start', 'change', 'change', 'end'], 'every change between one start and one end');
  assert.ok(calls.every((c) => c[1] === 't2'));
  near(trackOf('t2').volume, 0.6, 1e-9, 'the fader is where the drag left it');
  assert.equal(trackOf('t1').volume, 0.8);
  assert.deepEqual(groupLog, ['begin', 'end']);
  assert.equal(undoSteps(), 1);
  assert.equal(chip('t2'), null, 'the readout goes with the drag');
  assert.equal(sel().selected, null);
  assert.deepEqual(seen, [], 'the lanes saw none of it');
  await step(() => store().undo());
  assert.equal(trackOf('t2').volume, 0.5, 'one undo takes the whole drag back');

  // A drag that only goes sideways is not a fader move at all.
  calls.length = 0;
  groupLog.length = 0;
  await step(() => {
    ptr(line, 'pointerdown', 1, 400, 59);
    ptr(line, 'pointermove', 1, 480, 60);
    ptr(line, 'pointerup', 1, 480, 60);
  });
  assert.deepEqual(calls, []);
  assert.deepEqual(groupLog, []);

  // Past unity the fader stops, and it picks up again where the pointer comes back to the band.
  calls.length = 0;
  await step(() => {
    ptr(line, 'pointerdown', 1, 400, 59);
    ptr(line, 'pointermove', 1, 400, -100);
    ptr(line, 'pointermove', 1, 400, -60);
    ptr(line, 'pointermove', 1, 400, 31);
    ptr(line, 'pointerup', 1, 400, 31);
  });
  assert.deepEqual(calls.map((c) => c[0]), ['start', 'change', 'change', 'end'], 'a move that changes nothing reports nothing');
  assert.equal(sentVolume(1), 1, 'unity');
  near(sentVolume(2), 0.9, 1e-9, '28 px above the press');
}

/* ── Dragging the stretch between two keyframes ─────────────────────────────── */

// The stretch between two keyframes drags up and down as one, and stops as a
// whole when its loudest keyframe reaches unity.
{
  await reset([lane('t1', [{ t: 2, v: 0.3 }, { t: 4, v: 0.6 }, { t: 6, v: 0.9 }])]);
  const line = hit('t1');
  const y = yAt(0.45);
  await step(() => { ptr(line, 'pointerdown', 0, 300, y); });
  assert.equal(sel().selected, null, 'a press on the line selects nothing');
  await step(() => { ptr(line, 'pointermove', 0, 300, y - 14); });
  near(pointsOf('t1')[0].v, 0.5, 1e-9, 'the keyframe before the pointer');
  near(pointsOf('t1')[1].v, 0.8, 1e-9, 'and the one after it, by the same amount');
  assert.equal(pointsOf('t1')[2].v, 0.9, 'the rest of the line stays');
  assert.equal(chip('t1')?.textContent, '-3.7 dB', 'the readout is the line under the press: 0.65');
  await step(() => { ptr(line, 'pointermove', 0, 300, y - 70); });
  near(pointsOf('t1')[0].v, 0.7, 1e-9, 'the pair keeps its difference');
  assert.equal(pointsOf('t1')[1].v, 1, 'and stops when its loudest keyframe is at unity');
  await step(() => { ptr(line, 'pointerup', 0, 300, y - 70); });
  assert.deepEqual(pointsOf('t1').map((p) => p.t), [2, 4, 6], 'no keyframe moved in time');
  assert.deepEqual(groupLog, ['begin', 'end']);
  assert.equal(undoSteps(), 1);
  assert.deepEqual(calls, [], 'the fader was not touched');
  await step(() => store().undo());
  assert.deepEqual(pointsOf('t1').map((p) => p.v), [0.3, 0.6, 0.9]);

  // Before the first keyframe and after the last, the flat run belongs to that keyframe alone.
  await step(() => {
    ptr(line, 'pointerdown', 0, 100, yAt(0.3));
    ptr(line, 'pointermove', 0, 100, yAt(0.3) - 7);
    ptr(line, 'pointerup', 0, 100, yAt(0.3) - 7);
  });
  near(pointsOf('t1')[0].v, 0.4, 1e-9, 'the first keyframe');
  assert.deepEqual(pointsOf('t1').slice(1).map((p) => p.v), [0.6, 0.9]);
  await step(() => {
    ptr(line, 'pointerdown', 0, 800, yAt(0.9));
    ptr(line, 'pointermove', 0, 800, yAt(0.9) + 14);
    ptr(line, 'pointerup', 0, 800, yAt(0.9) + 14);
  });
  near(pointsOf('t1')[2].v, 0.7, 1e-9, 'the last keyframe');
  assert.equal(pointsOf('t1')[1].v, 0.6);
}

// A line with more keyframes than handles (a recorded ride): the stretch that
// moves is the one between the two HANDLES on either side of the pointer.
{
  // Exact binary fractions, so the 10 px thinning is exact: a keyframe every 2 px at 64 px/s.
  const ride = Array.from({ length: 17 }, (_, k) => ({ t: 1 + k / 32, v: 0.5 }));
  assert.deepEqual(grabbedKeyframes([], 64, 1), [], 'no keyframes: the press is on the fader');
  assert.deepEqual(grabbedKeyframes(ride.slice(0, 1), 64, 0.5), [0]);
  const sparse = [{ t: 1, v: 0.5 }, { t: 2, v: 0.5 }, { t: 3, v: 0.5 }];
  assert.deepEqual(grabbedKeyframes(sparse, 64, 2.5), [1, 2], 'every keyframe has a handle: the two that bracket the pointer');
  assert.deepEqual(grabbedKeyframes(sparse, 64, 0.5), [0]);
  assert.deepEqual(grabbedKeyframes(sparse, 64, 3.5), [2]);
  // Handles on keyframes 0, 5, 10 and 15. The pointer is between keyframes 3 and 4.
  assert.deepEqual(grabbedKeyframes(ride, 64, 1 + 3.5 / 32), [0, 1, 2, 3, 4, 5], 'from the handle before the pointer to the handle after it');
  assert.deepEqual(grabbedKeyframes(ride, 64, 1 + 7.5 / 32), [5, 6, 7, 8, 9, 10]);
  assert.deepEqual(grabbedKeyframes(ride, 64, 9), [15, 16], 'past the end: the last handle and the keyframe hidden after it');
  // The selected keyframe always has a handle, and takes the place of the ones beside it.
  assert.deepEqual(grabbedKeyframes(ride, 64, 1 + 3.5 / 32, 3), [3, 4, 5, 6, 7, 8, 9, 10]);

  // Mounted: a keyframe every 3 px at 100 px/s has handles on 0, 4 and 8.
  await reset([lane('t1', Array.from({ length: 9 }, (_, k) => ({ t: 5 + k * 0.03, v: 0.5 })))]);
  assert.deepEqual(handles('t1').map((el) => el.getAttribute('data-volume-keyframe')), ['0', '4', '8']);
  const line = hit('t1');
  await step(() => {
    ptr(line, 'pointerdown', 0, 505, 59);
    ptr(line, 'pointermove', 0, 505, 45);
    ptr(line, 'pointerup', 0, 505, 45);
  });
  assert.deepEqual(pointsOf('t1').map((p) => Math.round(p.v * 10) / 10), [0.7, 0.7, 0.7, 0.7, 0.7, 0.5, 0.5, 0.5, 0.5], 'the whole stretch between the two handles');
  assert.equal(pointsOf('t1').length, 9, 'no keyframe was merged away');
  assert.equal(undoSteps(), 1, 'one undo step, however many keyframes moved');
}

/* ── Keys ───────────────────────────────────────────────────────────────────── */

// The arrow keys nudge the selected keyframe, and the timeline's own shortcuts
// do not also run. Delete removes it.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }])]);
  await step(() => { sel().select({ trackId: 't1', t: 2.5 }); });
  const s = svg('t1');
  await step(() => { s.focus(); });
  windowKeys.length = 0;
  let notPrevented = true;
  await step(() => { notPrevented = key(s, 'ArrowUp'); });
  assert.equal(formatVolumeDb(pointsOf('t1')[0].v), '-1.8 dB', 'ArrowUp raises it 0.1 dB');
  near(gainToDb(pointsOf('t1')[0].v), -1.8, 1e-9, 'onto a clean tenth');
  assert.equal(notPrevented, false);
  assert.deepEqual(windowKeys, [], 'the key stops at the line');
  assert.equal(s.getAttribute('aria-valuetext'), '-1.8 dB at 00:02.500', 'the slider value follows');
  await step(() => { key(s, 'ArrowDown', { shiftKey: true }); });
  near(gainToDb(pointsOf('t1')[0].v), -2.8, 1e-9, 'Shift is a whole dB');
  assert.equal(undoSteps(), 1, 'a run of presses is one undo step');

  await step(() => { key(s, 'ArrowRight'); });
  assert.equal(pointsOf('t1')[0].t, 2.75, 'one step of the grid to the right');
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.75 }, 'the selection follows');
  await step(() => { key(s, 'ArrowLeft', { shiftKey: true }); });
  assert.equal(pointsOf('t1')[0].t, 1.75, 'Shift is the coarse step');

  // Ctrl, Cmd and Alt combinations are left to the app.
  const lanes = store().automationLanes;
  await step(() => {
    notPrevented = key(s, 'ArrowUp', { ctrlKey: true });
    key(s, 'ArrowUp', { metaKey: true });
    key(s, 'ArrowUp', { altKey: true });
  });
  assert.equal(store().automationLanes, lanes);
  assert.equal(notPrevented, true);
  assert.deepEqual(windowKeys, ['ArrowUp', 'ArrowUp', 'ArrowUp']);

  windowKeys.length = 0;
  await step(() => { key(s, 'Delete'); });
  assert.deepEqual(pointsOf('t1'), [], 'Delete removes the keyframe');
  assert.equal(sel().selected, null);
  assert.deepEqual(windowKeys, [], 'and does not also reach the clips');
  assert.ok(volumeLaneOf(store().automationLanes, 't1'), 'the empty lane stays');
  assert.equal(stroke('t1').getAttribute('points'), '0.0,38.0 1000.0,38.0', 'the line is the fader again');
  // With nothing selected the same key is the app's.
  await step(() => { notPrevented = key(s, 'Delete'); });
  assert.equal(notPrevented, true);
  assert.deepEqual(windowKeys, ['Delete']);
}

// Home, End, Page Up and Page Down walk the keyframes. Escape deselects.
{
  await reset([lane('t1', [{ t: 2, v: 0.3 }, { t: 4, v: 0.6 }, { t: 6, v: 0.9 }])]);
  const s = svg('t1');
  await step(() => { s.focus(); });
  windowKeys.length = 0;
  assert.equal(s.getAttribute('aria-valuetext'), 'No keyframe selected');
  assert.equal(s.getAttribute('aria-valuenow'), '0.3', 'the first keyframe stands in');
  await step(() => { key(s, 'PageDown'); });
  assert.equal(sel().selected?.t, 2, 'with none selected, Page Down is the first');
  await step(() => { key(s, 'PageDown'); });
  assert.equal(sel().selected?.t, 4);
  await step(() => { key(s, 'End'); });
  assert.equal(sel().selected?.t, 6);
  assert.equal(s.getAttribute('aria-valuenow'), '0.9', 'the slider value is the selected keyframe');
  assert.equal(s.getAttribute('aria-valuetext'), '-0.9 dB at 00:06.000');
  await step(() => { key(s, 'PageDown'); });
  assert.equal(sel().selected?.t, 6, 'the last stays the last');
  await step(() => { key(s, 'PageUp'); });
  assert.equal(sel().selected?.t, 4);
  await step(() => { key(s, 'Home'); });
  assert.equal(sel().selected?.t, 2);
  assert.equal(s.getAttribute('aria-valuenow'), '0.3');
  assert.equal(s.getAttribute('aria-valuetext'), '-10.5 dB at 00:02.000');
  await step(() => { sel().select(null); });
  await step(() => { key(s, 'PageUp'); });
  assert.equal(sel().selected?.t, 6, 'with none selected, Page Up is the last');
  assert.deepEqual(windowKeys, [], 'every one of them stayed with the line');
  assert.ok(calls.length > 0 && calls.every((c) => c[0] === 'selected'), 'each selection tells the editor');

  await step(() => { key(s, 'Escape'); });
  assert.equal(sel().selected, null, 'Escape deselects');
  assert.deepEqual(windowKeys, []);
  await step(() => { key(s, 'Escape'); });
  assert.deepEqual(windowKeys, ['Escape'], 'with nothing selected Escape is the timeline\'s');
  // No keyframe selected on a line that has some: the arrows are the app's.
  await step(() => { key(s, 'ArrowUp'); });
  assert.deepEqual(windowKeys, ['Escape', 'ArrowUp']);
  assert.deepEqual(pointsOf('t1').map((p) => p.v), [0.3, 0.6, 0.9]);
  assert.equal(undoSteps(), 0, 'selecting is not an edit');
}

// With no keyframes Up and Down move the fader: one start, one change and one end a press.
{
  await reset();
  const s = svg('t2');
  await step(() => { s.focus(); });
  windowKeys.length = 0;
  await step(() => { key(s, 'ArrowUp'); });
  assert.deepEqual(calls.map((c) => c[0]), ['start', 'change', 'end']);
  assert.equal(formatVolumeDb(sentVolume(1)), '-5.9 dB', '0.5 is -6.02 dB, and one press up is -5.9');
  assert.equal(formatVolumeDb(trackOf('t2').volume), '-5.9 dB');
  await step(() => { key(s, 'ArrowDown', { shiftKey: true }); });
  assert.equal(formatVolumeDb(trackOf('t2').volume), '-6.9 dB');
  assert.deepEqual(windowKeys, []);
  assert.equal(calls.length, 6);
  assert.equal(s.getAttribute('aria-valuetext'), '-6.9 dB, no keyframes');
  // Left and Right have nothing to move on a bare line.
  await step(() => { key(s, 'ArrowLeft'); });
  assert.deepEqual(windowKeys, ['ArrowLeft']);
}

/* ── The value field ────────────────────────────────────────────────────────── */

// Enter opens a field on the selected keyframe. It has an id, a name and a
// real label, and "-6" commits as 0.501.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }])]);
  await step(() => { sel().select({ trackId: 't1', t: 2.5 }); });
  const s = svg('t1');
  await step(() => { s.focus(); });
  windowKeys.length = 0;
  await step(() => { key(s, 'Enter'); });
  const input = field('t1');
  assert.ok(input, 'Enter opens the value field');
  assert.equal(input.type, 'text');
  assert.equal(input.getAttribute('inputmode'), 'decimal');
  assert.ok(input.id, 'the field has an id');
  assert.equal(input.name, input.id, 'and a name');
  const label = q<HTMLLabelElement>(`label[for="${input.id}"]`);
  assert.equal(label?.textContent, 'Keyframe volume in decibels', 'and a real label');
  assert.match(label!.className, /\bsr-only\b/);
  assert.equal(input.value, '-1.9', 'prefilled with the number, no unit');
  assert.equal(win.document.activeElement, input, 'focused');
  assert.equal(input.selectionStart, 0);
  assert.equal(input.selectionEnd, 4, 'and selected, so typing replaces it');
  assert.ok(input.closest('[data-volume-keyframe-ui]'), 'inside the chip');
  assert.equal(row('t1').querySelector('button'), null, 'the field takes the chip key\'s place');

  await step(() => { type(input, '-6'); });
  assert.equal(pointsOf('t1')[0].v, 0.8, 'typing alone changes nothing');
  await step(() => { key(input, 'Enter'); });
  near(pointsOf('t1')[0].v, 0.5011872336, 1e-9, '-6 dB is 0.501');
  assert.equal(field('t1'), null, 'the field closes');
  assert.equal(win.document.activeElement, s, 'and the line has the keys back');
  assert.equal(chip('t1')?.textContent, '-6.0 dB');
  assert.equal(undoSteps(), 1, 'a typed value is one undo step');
  assert.deepEqual(windowKeys, [], 'neither Enter reached the timeline');
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.5 }, 'the keyframe stays selected');

  // The chip opens the field too. Escape cancels.
  await step(() => { row('t1').querySelector('button')!.click(); });
  assert.ok(field('t1'), 'a click on the chip opens the field');
  assert.equal(field('t1')!.value, '-6.0');
  await step(() => { type(field('t1')!, '-20'); });
  await step(() => { key(field('t1')!, 'Escape'); });
  assert.equal(field('t1'), null);
  near(pointsOf('t1')[0].v, 0.5011872336, 1e-9, 'Escape writes nothing');
  assert.equal(win.document.activeElement, s);
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.5 }, 'and deselects nothing');
  assert.deepEqual(windowKeys, []);

  // A double-click on the keyframe opens it. Text that is no level just closes it.
  await step(() => { mouse(handle('t1', 0)!, 'dblclick', 0, 250, yAt(0.5)); });
  assert.ok(field('t1'), 'a double-click on the keyframe opens the field');
  assert.deepEqual(seen, []);
  await step(() => { type(field('t1')!, 'loud'); });
  await step(() => { key(field('t1')!, 'Enter'); });
  assert.equal(field('t1'), null);
  near(pointsOf('t1')[0].v, 0.5011872336, 1e-9, 'unreadable text writes nothing');

  // The prefill is rounded to a tenth of a dB: 0.5 is -6.02 dB and reads
  // "-6.0", which is 0.5012. Committing it unchanged must not move the keyframe.
  await step(() => { store().updateAutomationPoint('lane-t1', 0, 2.5, 0.5); });
  beginUndoStep();
  const stepsBefore = undoSteps();
  const lanesBefore = store().automationLanes;
  await step(() => { key(s, 'Enter'); });
  assert.equal(field('t1')!.value, '-6.0');
  await step(() => { key(field('t1')!, 'Enter'); });
  assert.equal(store().automationLanes, lanesBefore, 'an unchanged field writes nothing');
  assert.equal(pointsOf('t1')[0].v, 0.5);
  assert.equal(undoSteps(), stepsBefore);
  // Typed again as it stands, it is a typed value and is taken at its word.
  await step(() => { key(s, 'Enter'); });
  await step(() => { type(field('t1')!, '-6'); });
  await step(() => { key(field('t1')!, 'Enter'); });
  near(pointsOf('t1')[0].v, 0.5011872336, 1e-9, '-6 dB');
  assert.equal(undoSteps(), stepsBefore + 1);

  // A blur commits, and leaves the focus where the user put it.
  await step(() => { key(s, 'Enter'); });
  await step(() => { type(field('t1')!, '-12 dB'); });
  await step(() => { field('t1')!.blur(); });
  assert.equal(field('t1'), null);
  assert.equal(formatVolumeDb(pointsOf('t1')[0].v), '-12.0 dB', 'a blur commits');
  assert.notEqual(win.document.activeElement, s, 'without pulling the focus back');
  assert.equal(undoSteps(), stepsBefore + 2, 'each typed value is its own undo step');

  // A press somewhere else while a value is being typed keeps the value and drops the selection.
  await step(() => { sel().setEditing(true); });
  await step(() => { type(field('t1')!, '-3'); });
  await step(() => { win.document.body.dispatchEvent(new win.PointerEvent('pointerdown', { bubbles: true, pointerId: 1 })); });
  assert.equal(formatVolumeDb(pointsOf('t1')[0].v), '-3.0 dB');
  assert.equal(sel().selected, null);
  assert.equal(field('t1'), null);
  assert.equal(sel().editing, false);
}

// A press on ANOTHER keyframe while a value is being typed: the typed value
// goes to the keyframe the field was opened on, not to the one just pressed.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }, { t: 6, v: 0.4 }])]);
  await step(() => { sel().select({ trackId: 't1', t: 2.5 }); });
  await step(() => { sel().setEditing(true); });
  await step(() => { type(field('t1')!, '-9'); });
  const other = handle('t1', 1)!;
  await step(() => { ptr(other, 'pointerdown', 0, 600, yAt(0.4)); });
  await step(() => { ptr(other, 'pointerup', 0, 600, yAt(0.4)); });
  assert.equal(formatVolumeDb(pointsOf('t1')[0].v), '-9.0 dB', 'the keyframe the field was on');
  assert.equal(pointsOf('t1')[1].v, 0.4, 'the pressed keyframe keeps its value');
  assert.deepEqual(sel().selected, { trackId: 't1', t: 6 }, 'and is the selected one now');
  assert.equal(field('t1'), null);
  assert.equal(win.document.activeElement, svg('t1'));

  // A press on the SAME keyframe: the typed value is committed first, and the
  // drag starts from it.
  await step(() => { sel().setEditing(true); });
  await step(() => { type(field('t1')!, '-20'); });
  await step(() => { ptr(other, 'pointerdown', 0, 600, yAt(0.4)); });
  near(pointsOf('t1')[1].v, 0.1, 1e-9, '-20 dB is 0.1');
  await step(() => { ptr(other, 'pointermove', 0, 600, yAt(0.4) - 14); });
  near(pointsOf('t1')[1].v, 0.3, 1e-9, 'the drag adds to the typed value, not to the one before it');
  await step(() => { ptr(other, 'pointerup', 0, 600, yAt(0.4) - 14); });

  // A field belongs to one keyframe. When the selection moves on with the
  // field still open, the next keyframe gets a field of its own: its own
  // number in it, and what is typed there goes to it.
  await step(() => { sel().setEditing(true); });
  await step(() => { type(field('t1')!, '-40'); });
  await step(() => {
    sel().select({ trackId: 't1', t: 2.5 });
    sel().setEditing(true);
  });
  assert.equal(field('t1')!.value, '-9.0', 'the field shows the keyframe it is on now');
  await step(() => { type(field('t1')!, '-12'); });
  await step(() => { key(field('t1')!, 'Enter'); });
  assert.equal(formatVolumeDb(pointsOf('t1')[0].v), '-12.0 dB');
  near(pointsOf('t1')[1].v, 0.3, 1e-9, 'the keyframe the first field was on is untouched');
}

/* ── The keyframe menu ──────────────────────────────────────────────────────── */

// A right-click on a keyframe selects it and opens its menu.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.5 }, { t: 6, v: 0.8 }])]);
  const openMenu = async () => {
    let notPrevented = true;
    await step(() => { notPrevented = mouse(handle('t1', 0)!, 'contextmenu', 0, 250, 59); });
    return notPrevented;
  };
  assert.equal(await openMenu(), false, 'the browser menu does not open');
  assert.deepEqual(seen, [], 'nor the lanes\' own menu');
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.5 });
  assert.ok(menu(), 'the keyframe menu is open');
  assert.match(menu()!.textContent ?? '', /Keyframe at 00:02\.500/, 'headed by where the keyframe is');
  assert.deepEqual(
    [...menu()!.querySelectorAll('button')].map((b) => b.textContent),
    ['Set volume-6.0 dB', 'Unity0.0 dB', 'DeleteDel', 'Bypass', 'Clear2 keyframes'],
  );
  assert.equal(menuRow('Bypass').getAttribute('aria-checked'), 'false');
  assert.equal(pointsOf('t1').length, 2, 'opening the menu adds nothing');
  assert.equal(undoSteps(), 0);

  await step(() => { menuRow('Unity').click(); });
  assert.equal(pointsOf('t1')[0].v, 1, 'Unity is 0.0 dB');
  assert.equal(menu(), null, 'a choice closes the menu');
  assert.equal(undoSteps(), 1);

  // Bypass switches the keyframes off and keeps them: the line draws dashed and grey.
  await openMenu();
  await step(() => { menuRow('Bypass').click(); });
  assert.equal(volumeLaneOf(store().automationLanes, 't1')?.enabled, false);
  assert.equal(pointsOf('t1').length, 2);
  assert.equal(stroke('t1').getAttribute('stroke'), '#a1a1aa');
  assert.equal(stroke('t1').getAttribute('stroke-dasharray'), '4 3');
  assert.equal(handle('t1', 1)!.parentElement!.querySelector('rect')!.getAttribute('fill'), '#a1a1aa', 'its keyframes go grey with it');
  await openMenu();
  assert.equal(menuRow('Bypass').getAttribute('aria-checked'), 'true', 'the menu says so');
  await step(() => { menuRow('Bypass').click(); });
  assert.equal(volumeLaneOf(store().automationLanes, 't1')?.enabled, true);
  assert.equal(stroke('t1').getAttribute('stroke-dasharray'), null);

  // Set volume opens the field, with the focus in it.
  await openMenu();
  await step(() => { menuRow('Set volume').click(); });
  assert.equal(menu(), null);
  assert.ok(field('t1'), 'Set volume opens the value field');
  assert.equal(win.document.activeElement, field('t1'), 'and the menu closing did not take the focus from it');
  await step(() => { key(field('t1')!, 'Escape'); });

  // The Menu key on the focused line opens the selected keyframe's menu.
  assert.equal(win.document.activeElement, svg('t1'));
  let notPrevented = true;
  await step(() => { notPrevented = svg('t1').dispatchEvent(new win.MouseEvent('contextmenu', { bubbles: true, cancelable: true })); });
  assert.equal(notPrevented, false);
  assert.ok(menu(), 'the keyboard reaches the menu');
  assert.deepEqual(seen, []);
  await step(() => { menuRow('Delete').click(); });
  assert.deepEqual(pointsOf('t1').map((p) => p.t), [6], 'Delete removes the keyframe the menu was opened on');
  assert.equal(sel().selected, null);
  // With no keyframe selected the Menu key is the timeline's.
  await step(() => { notPrevented = svg('t1').dispatchEvent(new win.MouseEvent('contextmenu', { bubbles: true, cancelable: true })); });
  assert.equal(notPrevented, true);
  assert.deepEqual(seen, ['contextmenu']);
  assert.equal(menu(), null);
  seen.length = 0;

  // The chip opens the same menu, and Clear removes every keyframe of the track.
  await step(() => { mouse(handle('t1', 0)!, 'contextmenu', 0, 600, yAt(0.8)); });
  await step(() => { menuRow('Delete'); menu()!.dispatchEvent(new win.KeyboardEvent('keydown', { key: 'Escape', bubbles: true })); });
  await step(() => { mouse(chip('t1')!.querySelector('button')!, 'contextmenu', 0, 620, yAt(0.8)); });
  assert.match(menu()?.textContent ?? '', /Keyframe at 00:06\.000/);
  assert.equal(menuRow('Clear').textContent, 'Clear1 keyframe');
  // The menu is a portal, and React hands a portal's events to its React
  // parents. A press on a row must not reach the lanes: there it would start
  // a marquee, and the marquee's pointer capture would eat the row's click.
  await step(() => {
    const clearRow = menuRow('Clear');
    clearRow.dispatchEvent(new win.PointerEvent('pointerdown', { bubbles: true, pointerId: 1, button: 0 }));
    clearRow.dispatchEvent(new win.PointerEvent('pointermove', { bubbles: true, pointerId: 1 }));
    clearRow.dispatchEvent(new win.PointerEvent('pointerup', { bubbles: true, pointerId: 1, button: 0 }));
  });
  assert.deepEqual(seen, [], 'a press on a menu row never reaches the lanes');
  assert.deepEqual(sel().selected, { trackId: 't1', t: 6 }, 'and leaves the selection for the row to act on');
  await step(() => { menuRow('Clear').click(); });
  assert.deepEqual(pointsOf('t1'), []);
  assert.equal(sel().selected, null);
  assert.deepEqual(seen, []);
}

/* ── A press somewhere else ─────────────────────────────────────────────────── */

// A press outside the line drops its selection and its focus, so Delete and
// the arrows cannot reach a keyframe after the user has clicked a clip. A
// press on a menu leaves both alone.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }]), lane('t2', [{ t: 4, v: 0.5 }])]);
  await step(() => { ptr(handle('t1', 0)!, 'pointerdown', 0, 250, 38); });
  await step(() => { ptr(handle('t1', 0)!, 'pointerup', 0, 250, 38); });
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.5 });
  assert.equal(win.document.activeElement, svg('t1'));

  const fakeMenu = win.document.createElement('div');
  fakeMenu.setAttribute('role', 'menu');
  win.document.body.appendChild(fakeMenu);
  await step(() => { fakeMenu.dispatchEvent(new win.PointerEvent('pointerdown', { bubbles: true, pointerId: 1 })); });
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.5 }, 'a press on a menu keeps the selection');
  assert.equal(win.document.activeElement, svg('t1'));
  fakeMenu.remove();
  // A press on the line's own chip keeps it too.
  await step(() => { chip('t1')!.dispatchEvent(new win.PointerEvent('pointerdown', { bubbles: true, pointerId: 1 })); });
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.5 });
  assert.deepEqual(seen, [], 'and does not start a marquee under it');
  // So does a press on the line itself: it selects nothing and deselects nothing.
  await step(() => { ptr(hit('t1'), 'pointerdown', 0, 700, 38); });
  await step(() => { ptr(hit('t1'), 'pointerup', 0, 700, 38); });
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.5 }, 'a press on the line keeps the selection');
  assert.equal(win.document.activeElement, svg('t1'));

  await step(() => { win.document.body.dispatchEvent(new win.PointerEvent('pointerdown', { bubbles: true, pointerId: 1 })); });
  assert.equal(sel().selected, null, 'a press anywhere else drops the selection');
  assert.notEqual(win.document.activeElement, svg('t1'), 'and the focus');

  // A press on another track's keyframe moves the selection there.
  await step(() => { ptr(handle('t1', 0)!, 'pointerdown', 0, 250, 38); });
  await step(() => { ptr(handle('t1', 0)!, 'pointerup', 0, 250, 38); });
  await step(() => { ptr(handle('t2', 0)!, 'pointerdown', 1, 400, 59); });
  await step(() => { ptr(handle('t2', 0)!, 'pointerup', 1, 400, 59); });
  assert.deepEqual(sel().selected, { trackId: 't2', t: 4 }, 'one selection across every track');
  assert.equal(win.document.activeElement, svg('t2'));
  assert.equal(chip('t1'), null);
  assert.ok(chip('t2'));
  // A focused line with no selection gives the focus up the same way.
  await step(() => { sel().select(null); });
  assert.equal(win.document.activeElement, svg('t2'));
  await step(() => { win.document.body.dispatchEvent(new win.PointerEvent('pointerdown', { bubbles: true, pointerId: 1 })); });
  assert.notEqual(win.document.activeElement, svg('t2'));
}

/* ── One teardown, however the drag ends ────────────────────────────────────── */

// A lost capture, a cancel, a release that lands off the line, the cut tool
// and an unmount all end the drag, and each closes its undo group exactly once.
{
  const oneDrag = async (end: () => void | Promise<void>) => {
    await reset([lane('t1', [{ t: 2.5, v: 0.8 }])]);
    const h = handle('t1', 0)!;
    await step(() => { ptr(h, 'pointerdown', 0, 250, 38); });
    await step(() => { ptr(h, 'pointermove', 0, 250, 52); });
    near(pointsOf('t1')[0].v, 0.6, 1e-9, 'the drag is in flight');
    assert.deepEqual(groupLog, ['begin']);
    await end();
    assert.deepEqual(groupLog, ['begin', 'end'], 'closed once');
    near(pointsOf('t1')[0].v, 0.6, 1e-9, 'what the drag wrote stays');
    // The group really is closed: two later edits are two undo steps.
    const steps = undoSteps();
    await step(() => {
      store().updateTrack('t2', { volume: 0.4 });
      beginUndoStep();
      store().updateTrack('t2', { volume: 0.3 });
    });
    assert.equal(undoSteps(), steps + 2);
    return h;
  };

  let h = await oneDrag(() => step(() => { handle('t1', 0)!.dispatchEvent(new win.PointerEvent('lostpointercapture', { bubbles: true, pointerId: 1 })); }));
  await step(() => { ptr(h, 'pointermove', 0, 250, 80); });
  near(pointsOf('t1')[0].v, 0.6, 1e-9, 'a move after the capture is lost drags nothing');
  assert.deepEqual(groupLog, ['begin', 'end']);

  await oneDrag(() => step(() => { ptr(handle('t1', 0)!, 'pointercancel', 0, 250, 52); }));

  // The release lands on something else: the capture was lost and nobody said so.
  await oneDrag(() => step(() => { win.document.body.dispatchEvent(new win.PointerEvent('pointerup', { bubbles: true, pointerId: 1 })); }));
  // Another pointer's release is not this drag's.
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }])]);
  h = handle('t1', 0)!;
  await step(() => { ptr(h, 'pointerdown', 0, 250, 38); });
  await step(() => { ptr(h, 'pointermove', 0, 250, 52); });
  await step(() => { win.document.body.dispatchEvent(new win.PointerEvent('pointerup', { bubbles: true, pointerId: 2 })); });
  assert.deepEqual(groupLog, ['begin'], 'still dragging');
  await step(() => { ptr(h, 'pointerup', 0, 250, 52); });
  assert.deepEqual(groupLog, ['begin', 'end']);

  // The cut tool takes the pointer away mid-drag.
  await oneDrag(() => mount({ interactive: false }));
  await mount();

  // A press whose release was never seen ends when the next press comes.
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }])]);
  h = handle('t1', 0)!;
  await step(() => { ptr(h, 'pointerdown', 0, 250, 38); });
  await step(() => { ptr(h, 'pointermove', 0, 250, 52); });
  await step(() => { ptr(hit('t2'), 'pointerdown', 1, 400, 59); });
  assert.deepEqual(groupLog, ['begin'], 'another line is another gesture');
  await step(() => { ptr(hit('t2'), 'pointerup', 1, 400, 59); });
  await step(() => { ptr(h, 'pointerdown', 0, 250, 52); });
  assert.deepEqual(groupLog, ['begin', 'end'], 'the same line: the stale drag is closed before the new press');
  await step(() => { ptr(h, 'pointerup', 0, 250, 52); });
  assert.deepEqual(groupLog, ['begin', 'end']);

  // The line leaves the page mid-drag (its track is deleted, EDIT closes).
  await reset();
  await step(() => { ptr(hit('t2'), 'pointerdown', 1, 400, 59); });
  await step(() => { ptr(hit('t2'), 'pointermove', 1, 400, 45); });
  assert.deepEqual(calls.map((c) => c[0]), ['start', 'change']);
  await step(() => root.unmount());
  assert.deepEqual(calls.map((c) => c[0]), ['start', 'change', 'end'], 'the fader gesture is ended');
  assert.deepEqual(groupLog, ['begin', 'end'], 'and its undo group closed, once');
  windowKeys.length = 0;
  await step(() => { key(win.document.body, 'Escape'); });
  assert.deepEqual(windowKeys, ['Escape'], 'the drag\'s Escape listener went with it');
  near(trackOf('t2').volume, 0.7, 1e-9, 'so Escape takes nothing back');

  root = createRoot(host);
  await mount();
}

/* ── The cut tool ───────────────────────────────────────────────────────────── */

// With the cut tool active the lines are drawn and nothing in them takes the
// pointer or the Tab key.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }, { t: 6, v: 0.4 }])]);
  await step(() => { sel().select({ trackId: 't1', t: 2.5 }); });
  await step(() => { sel().setEditing(true); });
  assert.ok(field('t1'));
  await mount({ interactive: false });
  for (const id of ['t1', 't2']) {
    assert.match(row(id).className, /\bpointer-events-none\b/);
    assert.equal(svg(id).style.pointerEvents, 'none');
    assert.equal(svg(id).getAttribute('tabindex'), '-1', 'out of the Tab order');
    assert.equal(svg(id).getAttribute('aria-disabled'), 'true', 'and says it cannot be operated');
    for (const el of row(id).querySelectorAll('polyline, circle, rect')) {
      assert.equal(el.getAttribute('pointer-events'), 'none', `${el.tagName} takes no pointer`);
    }
    assert.equal(row(id).querySelector('.pointer-events-auto'), null);
    assert.equal(row(id).querySelector('button, input'), null, 'no control is left to press');
  }
  assert.equal(handles('t1').length, 2, 'the keyframes are still drawn');
  assert.equal(chip('t1')?.textContent, '-1.9 dB', 'and the selected one still reads its value');
  assert.equal(sel().editing, false, 'the value field closed');
  // The keys are the app's while the line is switched off.
  windowKeys.length = 0;
  await step(() => { key(svg('t1'), 'Delete'); });
  assert.equal(pointsOf('t1').length, 2);
  assert.deepEqual(windowKeys, ['Delete']);
  await mount();
  assert.equal(hit('t1').getAttribute('pointer-events'), 'stroke');
  assert.equal(svg('t1').getAttribute('tabindex'), '0');
  assert.equal(svg('t1').getAttribute('aria-disabled'), null);
}

/* ── The chip at the edge of the view ───────────────────────────────────────── */

// A chip that would pass the right edge of the view sits on the keyframe's
// left, and one near the top of the row stays inside the row.
{
  await reset([lane('t1', [{ t: 9.8, v: 1 }])]);
  await step(() => { sel().select({ trackId: 't1', t: 9.8 }); });
  const c = chip('t1')!;
  assert.equal(c.style.left, '970px', '10 px to the LEFT of the keyframe');
  assert.equal(c.style.transform, 'translateX(-100%)');
  assert.equal(c.style.top, '14px', 'centred on the keyframe at the band top');
  assert.equal(svg('t1').getAttribute('aria-valuetext'), '0.0 dB at 00:09.800');
}

/* ── Folder rows ────────────────────────────────────────────────────────────── */

// A folder is a row with no audio of its own, so it draws no line. The tracks
// after it keep their rows.
{
  await reset();
  await step(() => {
    useEditorStore.setState({
      tracks: [track({}), track({ id: 'f1', name: 'Strings', isFolder: true }), track({ id: 't2', name: 'Bass', volume: 0.5, parentTrackId: 'f1' })],
    });
  });
  assert.equal(q('[data-volume-line="f1"]'), null, 'no line on the folder row');
  assert.equal(row('t1').style.top, '0px');
  assert.equal(row('t2').style.top, `${ROW * 2}px`, 'the track inside the folder is on the third row');
  // Its line still answers where it is drawn.
  await step(() => { mouse(hit('t2'), 'contextmenu', 2, 300, 59); });
  assert.deepEqual(pointsOf('t2'), [{ t: 3, v: 0.5 }]);
}

/* ── CSS zoom ───────────────────────────────────────────────────────────────── */

// At 1920x1080 the shell's CSS zoom is 1.1, so a client point is the row's own
// point times 1.1. The line takes the zoom out: a keyframe lands under the
// pointer and a drag moves the value by what the pointer travelled on screen.
{
  await reset();
  Z = 1.1;
  await step(() => { host.style.zoom = String(Z); });
  await step(() => { mouse(hit('t2'), 'contextmenu', 1, 300, 59); });
  near(pointsOf('t2')[0].t, 3, 1e-9, 'the keyframe is at the time drawn under the pointer');
  const h = handle('t2', 0)!;
  await step(() => {
    ptr(h, 'pointerdown', 1, 300, 59);
    ptr(h, 'pointermove', 1, 300, 45);
    ptr(h, 'pointerup', 1, 300, 45);
  });
  near(pointsOf('t2')[0].v, 0.7, 1e-9, '14 row px up is +0.2, whatever the zoom');
  await step(() => { host.style.zoom = ''; });
  Z = 1;
}

/* ── Leaving the page ───────────────────────────────────────────────────────── */

// The lines leave the page (the AUTO editor takes over, EDIT closes) with a
// value field open: the field closes with them, the selection stays.
{
  await reset([lane('t1', [{ t: 2.5, v: 0.8 }])]);
  await step(() => { sel().select({ trackId: 't1', t: 2.5 }); });
  await step(() => { sel().setEditing(true); });
  assert.ok(field('t1'));
  await step(() => root.unmount());
  assert.equal(sel().editing, false, 'a field does not outlive its line');
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.5 }, 'the selection is there when the line comes back');
  assert.deepEqual(pointsOf('t1'), [{ t: 2.5, v: 0.8 }]);
}

console.log('TrackVolumeLine: ok');
