/**
 * The EDIT volume line's keyframes (state/volumeKeyframes), driven against the
 * REAL editor store: a keyframe is a point of the track's trackVolume
 * automation lane, and every edit is one undo step.
 *
 * The sequence each block replays:
 *   - the first keyframe on a track creates its lane at the fader's value, and
 *     one undo takes back both;
 *   - a keyframe added to a line that has some lands ON the line, so the line
 *     does not move;
 *   - a selected keyframe is nudged in dB, typed to a value, moved in time
 *     against its neighbours, and deleted;
 *   - a track's keyframes are cleared and bypassed;
 *   - a selection whose keyframe is gone resolves to nothing.
 *
 * Run: `node node_modules/tsx/dist/cli.mjs src/state/volumeKeyframes.test.ts`
 * (`npm test` discovers it).
 */
import assert from 'node:assert/strict';
import {
  beginUndoStep, sampleLane, useEditorStore,
  type AutomationLane, type AutomationPoint, type EditorTrack,
} from './editorStore.ts';
import { sampleCurve } from '../lib/automationModes.ts';
import {
  dbToGain, formatVolumeDb, gainToDb,
  KEYFRAME_DRAG_GAP_SEC, KEYFRAME_NUDGE_DB, KEYFRAME_NUDGE_DB_COARSE,
} from '../lib/volumeLine.ts';
import {
  addVolumeKeyframe, clearVolumeKeyframes, deleteVolumeKeyframe, keyframeIndexAt,
  moveVolumeKeyframeTime, nudgeVolumeKeyframe, resolveSelectedKeyframe, resolveVolumeKeyframe,
  setVolumeKeyframeValue, toggleVolumeKeyframesBypass, useVolumeKeyframes, volumeLaneOf, volumeTarget,
  type VolumeKeyframeRef,
} from './volumeKeyframes.ts';

const st = () => useEditorStore.getState();
const sel = () => useVolumeKeyframes.getState();

const near = (a: number, b: number, eps: number, msg: string): void =>
  assert.ok(Math.abs(a - b) <= eps, `${msg} (${a} !~ ${b})`);

const track = (over: Partial<EditorTrack> = {}): EditorTrack => ({
  id: 't1', name: 'T1', nameAutoGenerated: false, volume: 0.8, pan: 0,
  mute: false, solo: false, color: '#fff', ...over,
});

const lane = (trackId: string, points: AutomationPoint[], enabled = true): AutomationLane =>
  ({ id: `lane-${trackId}`, target: volumeTarget(trackId), points, enabled });

const laneOf = (trackId = 't1'): AutomationLane | undefined => volumeLaneOf(st().automationLanes, trackId);
const pointsOf = (trackId = 't1'): AutomationPoint[] => laneOf(trackId)?.points ?? [];
const dbOf = (index: number, trackId = 't1'): number => gainToDb(pointsOf(trackId)[index].v);

/** Put the store in a known document state with two tracks (faders at 0.8 and
 *  0.5), start counting undo steps from zero and drop the selection. The
 *  `_undo` reset is its own `setState` so the history recorder skips it, and
 *  `beginUndoStep` cuts the 300 ms burst the setup itself opened. */
const reset = (over: Partial<Parameters<typeof useEditorStore.setState>[0]> = {}): void => {
  useEditorStore.setState({
    tracks: [track(), track({ id: 't2', name: 'T2', volume: 0.5 })],
    clips: [],
    masterFxChain: [],
    automationLanes: [],
    automationHolds: {},
    automationMode: 'read',
    ...over,
  } as never);
  useEditorStore.setState({ _undo: [], _redo: [] });
  beginUndoStep();
  useVolumeKeyframes.setState({ selected: null, editing: false });
};

const undoSteps = (): number => st()._undo.length;

// ── The selection ────────────────────────────────────────────────────────────

// One keyframe at most, named by track and time. The value field belongs to it.
{
  reset();
  assert.equal(sel().selected, null);
  assert.equal(sel().editing, false);
  sel().setEditing(true);
  assert.equal(sel().editing, false, 'with nothing selected the value field cannot open');

  sel().select({ trackId: 't1', t: 2 });
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2 });
  sel().setEditing(true);
  assert.equal(sel().editing, true);
  sel().retime(2.5);
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2.5 }, 'the selection follows a keyframe that moved in time');
  assert.equal(sel().editing, true, 'and a move does not close the field');

  sel().select({ trackId: 't1', t: 2.5 });
  assert.equal(sel().editing, false, 'selecting closes the field');
  const before = useVolumeKeyframes.getState();
  sel().select({ trackId: 't1', t: 2.5 });
  assert.ok(Object.is(useVolumeKeyframes.getState(), before), 'selecting the selected keyframe wakes no subscriber');

  sel().select(null);
  assert.equal(sel().selected, null);
  sel().retime(9);
  assert.equal(sel().selected, null, 'a move with nothing selected selects nothing');
}

// ── Adding ───────────────────────────────────────────────────────────────────

// The first keyframe creates the lane at the fader's value, and ONE undo takes
// back both. The selection outlives the undo and resolves to nothing.
{
  reset();
  const ref = addVolumeKeyframe('t1', 2);
  assert.deepEqual(ref, { trackId: 't1', t: 2 });
  const made = laneOf();
  assert.ok(made, 'the first keyframe creates the lane');
  assert.deepEqual(made.target, { kind: 'trackVolume', trackId: 't1' });
  assert.equal(made.enabled, true);
  assert.deepEqual(made.points, [{ t: 2, v: 0.8 }], 'the keyframe sits at the fader value, so the line did not move');
  assert.deepEqual(sel().selected, ref, 'the new keyframe is selected');
  assert.equal(undoSteps(), 1, 'lane and keyframe are ONE undo step');
  const hit = resolveSelectedKeyframe();
  assert.ok(hit);
  assert.equal(hit.lane.id, made.id);
  assert.equal(hit.index, 0);
  assert.deepEqual(hit.point, { t: 2, v: 0.8 });

  st().undo();
  assert.deepEqual(st().automationLanes, [], 'one undo removes the keyframe AND the lane');
  assert.deepEqual(sel().selected, ref, 'the selection is not part of the history');
  assert.equal(resolveSelectedKeyframe(), null, 'a selection whose keyframe was undone resolves to nothing');
  st().redo();
  assert.deepEqual(resolveSelectedKeyframe()?.point, { t: 2, v: 0.8 }, 'and to the keyframe again once it is back');

  // Each track has its own line, at its own fader.
  const other = addVolumeKeyframe('t2', 1);
  assert.deepEqual(other, { trackId: 't2', t: 1 });
  assert.deepEqual(pointsOf('t2'), [{ t: 1, v: 0.5 }]);
  assert.deepEqual(pointsOf('t1'), [{ t: 2, v: 0.8 }], 'the first track is untouched');
  assert.deepEqual(sel().selected, other, 'one selection across every track');
}

// A keyframe added to a line that has some lands ON the line.
{
  const original = lane('t1', [{ t: 1, v: 0.2 }, { t: 3, v: 0.6 }]);
  reset({ automationLanes: [original] });
  const ref = addVolumeKeyframe('t1', 2);
  assert.deepEqual(ref, { trackId: 't1', t: 2 });
  assert.deepEqual(pointsOf().map((p) => p.t), [1, 2, 3], 'between the two it was added between');
  near(pointsOf()[1].v, 0.4, 1e-12, 'at the value the line had there');
  assert.equal(undoSteps(), 1);

  // Outside the keyframes the line holds the end value, and so does the new keyframe.
  addVolumeKeyframe('t1', 0.25);
  addVolumeKeyframe('t1', 9);
  assert.deepEqual(pointsOf().map((p) => p.t), [0.25, 1, 2, 3, 9]);
  assert.equal(pointsOf()[0].v, 0.2);
  assert.equal(pointsOf()[4].v, 0.6);
  assert.equal(undoSteps(), 3, 'each add is its own undo step, however fast it follows the last');
  for (const t of [0, 0.25, 0.6, 1, 1.5, 2, 2.5, 3, 5, 9, 12]) {
    near(sampleLane(laneOf()!, t) as number, sampleLane(original, t) as number, 1e-12, `the line moved at t=${t}`);
  }

  // A bent stretch is read through the sampler playback uses.
  const bent: AutomationPoint[] = [{ t: 0, v: 0, curve: 1 }, { t: 2, v: 1 }];
  reset({ automationLanes: [lane('t1', bent)] });
  addVolumeKeyframe('t1', 1);
  assert.equal(pointsOf()[1].v, sampleCurve(bent, 1), 'on the bend, not on the straight line under it');

  // An emptied lane has no say: the next keyframe is at the fader again.
  reset({ automationLanes: [lane('t1', [])] });
  addVolumeKeyframe('t1', 4);
  assert.deepEqual(pointsOf(), [{ t: 4, v: 0.8 }]);
  assert.equal(st().automationLanes.length, 1, 'the lane that was there is reused');
}

// What cannot be added, is not, and writes nothing.
{
  reset();
  assert.deepEqual(addVolumeKeyframe('t1', -3), { trackId: 't1', t: 0 }, 'a time before the timeline starts lands on 0');
  assert.deepEqual(pointsOf(), [{ t: 0, v: 0.8 }]);

  reset();
  sel().select({ trackId: 't2', t: 5 });
  assert.equal(addVolumeKeyframe('no-such-track', 1), null, 'an unknown track');
  assert.equal(addVolumeKeyframe('t1', Number.NaN), null, 'an unusable time');
  assert.deepEqual(st().automationLanes, [], 'neither left a lane behind');
  assert.equal(undoSteps(), 0);
  assert.deepEqual(sel().selected, { trackId: 't2', t: 5 }, 'nor touched the selection');
}

// A time inside the store's thinning window of a keyframe selects that keyframe
// and writes nothing. The store would fold the new point into it and overwrite
// its value, which on a steep stretch is not the value it had.
{
  reset({ automationLanes: [lane('t1', [{ t: 1, v: 0 }, { t: 1.05, v: 1 }])] });
  const before = st().automationLanes;
  const ref = addVolumeKeyframe('t1', 1.015);
  assert.deepEqual(ref, { trackId: 't1', t: 1 }, 'the keyframe that is already there');
  assert.equal(st().automationLanes, before, 'nothing was written');
  assert.equal(undoSteps(), 0);
  assert.deepEqual(sel().selected, { trackId: 't1', t: 1 });

  // Clear of both keyframes by more than the window, one IS added.
  const added = addVolumeKeyframe('t1', 1.025);
  assert.deepEqual(added, { trackId: 't1', t: 1.025 });
  assert.equal(pointsOf().length, 3);
  near(pointsOf()[1].v, 0.5, 1e-9, 'on the ramp');
}

// The window is the store's own and the store does not export it. Pinned from
// both sides, so a change to it there fails here.
{
  reset({ automationLanes: [lane('t1', [{ t: 1, v: 0.3 }])] });
  st().addAutomationPoint('lane-t1', 1.019, 0.9);
  assert.deepEqual(pointsOf(), [{ t: 1, v: 0.9 }], 'the store folds a point 19 ms away into its neighbour');
  st().addAutomationPoint('lane-t1', 1.021, 0.5);
  assert.equal(pointsOf().length, 2, 'and keeps one 21 ms away');

  reset({ automationLanes: [lane('t1', [{ t: 1, v: 0.3 }])] });
  assert.deepEqual(addVolumeKeyframe('t1', 1.019), { trackId: 't1', t: 1 });
  assert.deepEqual(pointsOf(), [{ t: 1, v: 0.3 }], 'the keyframe 19 ms away kept its value');
  assert.deepEqual(addVolumeKeyframe('t1', 1.021), { trackId: 't1', t: 1.021 });
  assert.equal(pointsOf().length, 2);
}

// ── The selected keyframe's volume ───────────────────────────────────────────

// The arrow keys: tenths of a dB, whole dB with Shift, and a held key is one undo step.
{
  reset({ automationLanes: [lane('t1', [{ t: 1, v: 0.5 }, { t: 3, v: 1 }])] });
  const ref: VolumeKeyframeRef = { trackId: 't1', t: 1 };
  nudgeVolumeKeyframe(ref, KEYFRAME_NUDGE_DB);
  near(dbOf(0), -5.9, 1e-9, 'one press up');
  assert.equal(undoSteps(), 1);
  for (let i = 0; i < 5; i += 1) nudgeVolumeKeyframe(ref, KEYFRAME_NUDGE_DB);
  near(dbOf(0), -5.4, 1e-9, 'five more');
  assert.equal(undoSteps(), 1, 'the repeats of a held key are ONE undo step');
  nudgeVolumeKeyframe(ref, -KEYFRAME_NUDGE_DB_COARSE);
  near(dbOf(0), -6.4, 1e-9, 'a whole dB down');
  nudgeVolumeKeyframe(ref, -KEYFRAME_NUDGE_DB);
  near(dbOf(0), -6.5, 1e-9, 'a tenth down');
  assert.equal(pointsOf()[0].t, 1, 'a volume nudge does not move the keyframe in time');
  assert.deepEqual(pointsOf()[1], { t: 3, v: 1 }, 'or touch another keyframe');

  st().undo();
  assert.deepEqual(pointsOf()[0], { t: 1, v: 0.5 }, 'one undo takes the whole run of presses back');

  // A press that changes nothing writes nothing: up at unity, down at silence,
  // and a keyframe that is not there.
  setVolumeKeyframeValue(ref, 0);
  const lanes = st().automationLanes;
  const steps = undoSteps();
  nudgeVolumeKeyframe({ trackId: 't1', t: 3 }, KEYFRAME_NUDGE_DB);
  nudgeVolumeKeyframe(ref, -KEYFRAME_NUDGE_DB);
  nudgeVolumeKeyframe({ trackId: 't1', t: 2 }, KEYFRAME_NUDGE_DB);
  assert.equal(st().automationLanes, lanes, 'the document is the same object');
  assert.equal(undoSteps(), steps, 'and there is no empty undo step');

  // From silence the first press up lands on the floor.
  nudgeVolumeKeyframe(ref, KEYFRAME_NUDGE_DB);
  assert.equal(formatVolumeDb(pointsOf()[0].v), '-60.0 dB');
}

// Right-click, then the arrow keys: the nudges are a step of their own, so one
// undo takes them back and leaves the keyframe that was added.
{
  reset();
  const ref = addVolumeKeyframe('t1', 2);
  assert.ok(ref);
  nudgeVolumeKeyframe(ref, -KEYFRAME_NUDGE_DB_COARSE);
  nudgeVolumeKeyframe(ref, -KEYFRAME_NUDGE_DB_COARSE);
  assert.equal(undoSteps(), 2, 'the add, then the run of presses');
  st().undo();
  assert.deepEqual(pointsOf(), [{ t: 2, v: 0.8 }], 'the keyframe is back at the value it was added at');
  st().undo();
  assert.deepEqual(st().automationLanes, []);
}

// A typed value is an undo step of its own on both sides.
{
  reset({ automationLanes: [lane('t1', [{ t: 1, v: 0.5, curve: 0.5 }, { t: 3, v: 1 }])] });
  const ref: VolumeKeyframeRef = { trackId: 't1', t: 1 };
  nudgeVolumeKeyframe(ref, KEYFRAME_NUDGE_DB);
  setVolumeKeyframeValue(ref, dbToGain(-12));
  assert.equal(undoSteps(), 2, 'it does not fold into the nudge it follows at once');
  assert.equal(formatVolumeDb(pointsOf()[0].v), '-12.0 dB');
  assert.equal(pointsOf()[0].curve, 0.5, 'the keyframe keeps the bend of the stretch it starts');
  nudgeVolumeKeyframe(ref, KEYFRAME_NUDGE_DB);
  assert.equal(undoSteps(), 3, 'and a nudge that follows it at once does not fold into it');
  st().undo();
  assert.equal(formatVolumeDb(pointsOf()[0].v), '-12.0 dB', 'undo takes back the nudge alone');
  st().undo();
  near(dbOf(0), -5.9, 1e-9, 'then the typed value alone');

  // The value is kept in 0..1.
  setVolumeKeyframeValue(ref, 7);
  assert.equal(pointsOf()[0].v, 1, 'above unity is unity');
  setVolumeKeyframeValue(ref, -2);
  assert.equal(pointsOf()[0].v, 0, 'below silence is silence');

  // Nothing to write: the value it already has, junk, a keyframe or track that is not there.
  const lanes = st().automationLanes;
  const steps = undoSteps();
  setVolumeKeyframeValue(ref, 0);
  setVolumeKeyframeValue(ref, Number.NaN);
  setVolumeKeyframeValue({ trackId: 't1', t: 2 }, 0.5);
  setVolumeKeyframeValue({ trackId: 'no-such-track', t: 1 }, 0.5);
  assert.equal(st().automationLanes, lanes);
  assert.equal(undoSteps(), steps);
}

// ── The selected keyframe's time ─────────────────────────────────────────────

// A time move stops at each neighbour, and the selection follows the keyframe.
{
  reset({ automationLanes: [lane('t1', [{ t: 1, v: 0.2 }, { t: 2, v: 0.6 }, { t: 3, v: 0.4 }])] });
  sel().select({ trackId: 't1', t: 2 });

  let ref = moveVolumeKeyframeTime({ trackId: 't1', t: 2 }, 0.25, 10);
  assert.deepEqual(ref, { trackId: 't1', t: 2.25 });
  assert.deepEqual(pointsOf().map((p) => p.t), [1, 2.25, 3]);
  assert.equal(pointsOf()[1].v, 0.6, 'the value rides along');
  assert.deepEqual(sel().selected, ref, 'the selection follows');
  assert.equal(resolveSelectedKeyframe()?.index, 1);

  ref = moveVolumeKeyframeTime(ref!, 5, 10);
  assert.ok(ref);
  near(ref.t, 3 - KEYFRAME_DRAG_GAP_SEC, 1e-12, 'held off the keyframe after it');
  assert.equal(pointsOf().length, 3, 'it did not merge into that keyframe');
  assert.deepEqual(sel().selected, ref);
  assert.equal(resolveSelectedKeyframe()?.index, 1, 'and did not pass it');

  // Against the stop there is nowhere to go: nothing moves and nothing is written.
  const lanes = st().automationLanes;
  assert.deepEqual(moveVolumeKeyframeTime(ref, 5, 10), ref);
  assert.equal(st().automationLanes, lanes);

  ref = moveVolumeKeyframeTime(ref, -5, 10);
  assert.ok(ref);
  near(ref.t, 1 + KEYFRAME_DRAG_GAP_SEC, 1e-12, 'held off the keyframe before it');
  assert.deepEqual(sel().selected, ref);
  assert.equal(undoSteps(), 1, 'a run of key moves is one undo step');

  // Moving a keyframe that is not the selected one leaves the selection alone.
  assert.deepEqual(moveVolumeKeyframeTime({ trackId: 't1', t: 3 }, 0.5, 10), { trackId: 't1', t: 3.5 });
  assert.deepEqual(sel().selected, ref);
  // The last keyframe stops at the end of the timeline, the first at 0.
  assert.deepEqual(moveVolumeKeyframeTime({ trackId: 't1', t: 3.5 }, 99, 10), { trackId: 't1', t: 10 });
  assert.deepEqual(moveVolumeKeyframeTime({ trackId: 't1', t: 1 }, -99, 10), { trackId: 't1', t: 0 });
  // A keyframe that is gone moves nowhere.
  assert.equal(moveVolumeKeyframeTime({ trackId: 't1', t: 7 }, 0.5, 10), null);
}

// ── Removing ─────────────────────────────────────────────────────────────────

// Delete removes one keyframe. The last one leaves the empty lane behind.
{
  reset({ automationLanes: [lane('t1', [{ t: 1, v: 0.2 }, { t: 2, v: 0.6 }])] });
  sel().select({ trackId: 't1', t: 2 });
  deleteVolumeKeyframe({ trackId: 't1', t: 1 });
  assert.deepEqual(pointsOf(), [{ t: 2, v: 0.6 }]);
  assert.deepEqual(sel().selected, { trackId: 't1', t: 2 }, 'deleting another keyframe leaves the selection');
  assert.equal(undoSteps(), 1);

  deleteVolumeKeyframe({ trackId: 't1', t: 2 });
  assert.deepEqual(pointsOf(), [], 'the last keyframe is gone');
  assert.ok(laneOf(), 'the empty lane stays');
  assert.equal(laneOf()?.enabled, true);
  assert.equal(sel().selected, null, 'the deleted keyframe was the selected one');
  assert.equal(undoSteps(), 2, 'each delete is its own undo step');

  // Nothing there to delete.
  const lanes = st().automationLanes;
  deleteVolumeKeyframe({ trackId: 't1', t: 2 });
  deleteVolumeKeyframe({ trackId: 'no-such-track', t: 2 });
  assert.equal(st().automationLanes, lanes);
  assert.equal(undoSteps(), 2);

  st().undo();
  assert.deepEqual(pointsOf(), [{ t: 2, v: 0.6 }], 'undo brings the keyframe back');
  assert.equal(sel().selected, null, 'unselected');
}

// Delete pressed while a drag is in flight. The drag holds an undo group open,
// and the delete joins it: the whole gesture is one undo step.
{
  reset({ automationLanes: [lane('t1', [{ t: 1, v: 0.5 }, { t: 3, v: 1 }])] });
  st().beginUndoGroup();
  st().updateAutomationPoint('lane-t1', 0, 1, 0.6);
  deleteVolumeKeyframe({ trackId: 't1', t: 3 });
  st().updateAutomationPoint('lane-t1', 0, 1, 0.7);
  st().endUndoGroup();
  assert.deepEqual(pointsOf(), [{ t: 1, v: 0.7 }]);
  assert.equal(undoSteps(), 1, 'the drag and the delete inside it are one undo step');
  st().undo();
  assert.deepEqual(pointsOf(), [{ t: 1, v: 0.5 }, { t: 3, v: 1 }], 'one undo puts back both');
}

// Clear removes every keyframe of one track.
{
  reset({ automationLanes: [lane('t1', [{ t: 1, v: 0.2 }, { t: 2, v: 0.6 }]), lane('t2', [{ t: 1, v: 0.9 }])] });
  sel().select({ trackId: 't1', t: 2 });
  clearVolumeKeyframes('t1');
  assert.deepEqual(pointsOf('t1'), []);
  assert.ok(laneOf('t1'), 'the empty lane stays');
  assert.deepEqual(pointsOf('t2'), [{ t: 1, v: 0.9 }], 'another track keeps its keyframes');
  assert.equal(sel().selected, null, 'the selection was on the cleared track');
  assert.equal(undoSteps(), 1);

  // A line with no keyframes, and a track with no line, write nothing.
  clearVolumeKeyframes('t1');
  clearVolumeKeyframes('no-such-track');
  assert.equal(undoSteps(), 1);

  st().undo();
  assert.deepEqual(pointsOf('t1'), [{ t: 1, v: 0.2 }, { t: 2, v: 0.6 }], 'one undo brings them all back');

  // A selection on another track survives.
  sel().select({ trackId: 't2', t: 1 });
  clearVolumeKeyframes('t1');
  assert.deepEqual(sel().selected, { trackId: 't2', t: 1 });
}

// Bypass switches the lane off and on and keeps its keyframes.
{
  reset({ automationLanes: [lane('t1', [{ t: 1, v: 0.2 }])] });
  toggleVolumeKeyframesBypass('t1');
  assert.equal(laneOf()?.enabled, false, 'bypassed: the fader has the gain');
  assert.deepEqual(pointsOf(), [{ t: 1, v: 0.2 }], 'the keyframes are kept');
  toggleVolumeKeyframesBypass('t1');
  assert.equal(laneOf()?.enabled, true);
  assert.equal(undoSteps(), 2, 'each switch is its own undo step');
  toggleVolumeKeyframesBypass('t2');
  assert.equal(st().automationLanes.length, 1, 'a track with no line has nothing to bypass');
  assert.equal(undoSteps(), 2);
}

// ── Resolving ────────────────────────────────────────────────────────────────

// A reference names a keyframe by track and time, and resolves to nothing once it is gone.
{
  const pan: AutomationLane = { id: 'lane-pan', target: { kind: 'trackPan', trackId: 't1' }, points: [{ t: 1, v: -0.5 }], enabled: true };
  reset({ automationLanes: [pan, lane('t2', [{ t: 1, v: 0.9 }]), lane('t1', [{ t: 1, v: 0.2 }, { t: 2, v: 0.6 }])] });
  assert.equal(volumeLaneOf(st().automationLanes, 't1')?.id, 'lane-t1', 'the volume lane, not the pan lane, of that track');
  assert.equal(volumeLaneOf(st().automationLanes, 'no-such-track'), undefined);

  const pts = pointsOf();
  assert.equal(keyframeIndexAt(pts, 2), 1);
  assert.equal(keyframeIndexAt(pts, 2 + 1e-7), 1, 'float drift under a microsecond is the same keyframe');
  assert.equal(keyframeIndexAt(pts, 2 + 1e-5), -1, 'anything further is not');
  assert.equal(keyframeIndexAt(pts, Number.NaN), -1);
  assert.equal(keyframeIndexAt([], 2), -1);

  assert.equal(resolveVolumeKeyframe(null), null);
  assert.equal(resolveVolumeKeyframe({ trackId: 't1', t: 1.5 }), null, 'no keyframe at that time');
  assert.deepEqual(resolveVolumeKeyframe({ trackId: 't2', t: 1 })?.point, { t: 1, v: 0.9 }, 'the same time on another track is another keyframe');

  sel().select({ trackId: 't1', t: 2 });
  assert.equal(resolveSelectedKeyframe()?.index, 1);
  st().removeAutomationLane('lane-t1');
  assert.equal(resolveSelectedKeyframe(), null, 'a selection whose lane was removed resolves to nothing');
  sel().select(null);
  assert.equal(resolveSelectedKeyframe(), null, 'and so does no selection');
}

console.log('volumeKeyframes: all assertions passed');
